import {
  AMEND_WORKFLOW_TOOL_NAME,
  CREATE_WORKFLOW_TOOL_NAME,
  RESUME_WORKFLOW_RUN_TOOL_NAME,
} from "@zcode/contracts";
import type {
  ExecutionPort,
  DynamicWorkflowRunSnapshot,
  SubagentTaskSnapshot,
  WorkflowTaskSnapshot,
} from "@zcode/contracts";
import {
  isTerminalRuntimeTask,
  type RuntimeTaskSnapshot,
  type RuntimeTaskType,
} from "../../runtime-task/registry.js";
import type { ExecutableToolCall } from "../types.js";
import type { ToolExecutorDeps } from "./types.js";
import { isRecord } from "./utils.js";
import { backgroundTaskOutputMetadata } from "./background-task-output.js";
import { serializeWorkflowArtifact } from "./workflow-artifact.js";

type BackgroundTaskSnapshot =
  | NonNullable<Awaited<ReturnType<NonNullable<ExecutionPort["getBackgroundTask"]>>>>
  | SubagentTaskSnapshot
  | WorkflowTaskSnapshot
  // The snapshot of workflow run follows the shape of WorkflowTaskSnapshot but relaxes the output to unknown (the product is generated by the script
  // Determined by the top-level return value), so it is not a subtype of WorkflowTaskSnapshot and must be listed separately.
  | DynamicWorkflowRunSnapshot;

/**
 * The name-dispatch predicate for dwf runs: CreateWorkflow = a fresh start / ResumeWorkflowRun = a resume, the two
 * entry points of the same run lifecycle, with snapshot/wait/cancel/notify/registry all isomorphic.
 *
 * Note: the Refine special case in CreateWorkflow's confirmation window (product-projection.ts / turn-control.ts)
 * deliberately does **not** switch to this predicate — ResumeWorkflowRun's confirmation window has no causalityGraph and
 * no graph refinement, so it takes the default ask; adding the name to those special cases would grow a graph-less
 * Refine option in the confirmation window.
 */
export function isDynamicWorkflowRunDispatchToolName(name: string): boolean {
  return (
    name === CREATE_WORKFLOW_TOOL_NAME ||
    name === AMEND_WORKFLOW_TOOL_NAME ||
    name === RESUME_WORKFLOW_RUN_TOOL_NAME
  );
}

export function registerRuntimeBackgroundTask(
  deps: ToolExecutorDeps,
  toolCall: ExecutableToolCall,
  taskId: string,
  output: Record<string, unknown>,
  turnId?: RuntimeTaskSnapshot["turnId"],
): void {
  const taskType = runtimeTaskTypeForToolCall(toolCall);
  if (!taskType || !deps.runtimeTaskRegistry) return;
  const existing = deps.runtimeTaskRegistry.get(taskId);
  const description = runtimeTaskDescription(toolCall, output) ?? defaultRuntimeTaskDescription(taskType);
  const outputFile = backgroundTaskOutputMetadata(output).outputFile;
  // The same process cancel final state → resume without restarting (dwf's resume heavy arm,
  // When the v4 command path and tool path are merged in trackBackgroundTask (the same problem), the existing entries carry the previous round of claim
  // notified: true, if the reconstruction is kept as it is, claimRuntimeBackgroundTaskNotification will be rejected based on this——
  // Restore run's final state model notification swallowed. The residue of the same family error/completedAt/resultText will also cause the running period
  // Entries are linked to old failures/old completion times/old products via the `??current.*` chain of updateRuntimeBackgroundTask.
  // Therefore, the overall reset **settlement surface** (notified/completedAt/error/exitCode/resultText/pid) when heavy arm;
  // **Identity side** remains existing??new (agentId/agentType/parentToolCallId/turnId/description/
  // startedAt)——parentToolCallId is the anchor of "Tool Card → Details Page Link Across Resume", which is replaced by this time
  // The descriptor id of the heavy arm will break the join.
  //
  // Resets must be bounded by **heavy arms**: only dwf dispatch names will be reused across resumes
  // runId starts a new life cycle (heavy arm) on the final entry. At this time, the last round of notified belongs to the old life cycle,
  // Must be voided. The task id of single life cycle tasks such as Bash/Agent is discarded after one round, but when the tracker is mounted late
  // register will also hit the final state entry that has been claimed (notified: true) - that is the claim of the same life cycle
  // Token, indiscriminate reset will cause model notifications in the same final state to be queued twice. "The defect name is irrelevant" refers to the reachable path
  // (The v4 command path also goes through the CreateWorkflow name), not any register should be reset.
  //
  // outputFile intentionally **not** resets with the calculation interface: workflow run never writes outputFile, existing is only a product
  // Transparent transmission reserved for externalization; when externalization is implemented, it should be re-determined according to its semantics (do not clear it or expand its semantics).
  const rearm = isDynamicWorkflowRunDispatchToolName(toolCall.name);
  // New life = heavy arm on the **final state** entry. It must use register() instead of update(): register will use the current
  // activeBranchGeneration overrides branchGeneration, and update's {...existing} will replace the previous life
  // The branch generation of the cycle brings new life - when cancel → rewind (branch generation +1) → resume, the task event of the new life will be
  // stale-branch fencing of runtime-command-generation when the old branch remains is discarded in its entirety (final state notifications are missing again).
  // Existing entries that are still running are not new, maintaining the merge semantics of update and its own branch generation.
  const newLife = rearm && existing !== undefined && isTerminalRuntimeTask(existing);
  const next: RuntimeTaskSnapshot = {
    ...existing,
    agentId: existing?.agentId ?? taskId,
    agentType: existing?.agentType ?? taskType,
    description: existing?.description ?? description,
    isBackgrounded: true,
    outputFile: outputFile ?? existing?.outputFile,
    parentToolCallId: existing?.parentToolCallId ?? toolCall.id,
    startedAt: existing?.startedAt ?? new Date(),
    status: "running",
    taskId,
    taskType,
    type: taskType,
    turnId: existing?.turnId ?? turnId,
    // ——Reset the settlement surface (only heavy arms = a new life cycle; remounting of non-heavy arms retains the existing settlement surface)——
    notified: rearm ? false : (existing?.notified ?? false),
    completedAt: rearm ? undefined : existing?.completedAt,
    error: rearm ? undefined : existing?.error,
    exitCode: rearm ? undefined : existing?.exitCode,
    resultText: rearm ? undefined : existing?.resultText,
    pid: rearm ? undefined : existing?.pid,
    // Who stopped the last round has nothing to do with the new life.
    stopInitiator: rearm ? undefined : existing?.stopInitiator,
  };
  if (existing && !newLife) {
    deps.runtimeTaskRegistry.update(taskId, () => next);
    return;
  }
  // First registration or new life: peel off the inherited branchGeneration and hand it to register to stamp according to the current active branch.
  const { branchGeneration: _previousLife, ...fresh } = next;
  deps.runtimeTaskRegistry.register(fresh);
}

export function updateRuntimeBackgroundTask(
  deps: ToolExecutorDeps,
  toolCall: ExecutableToolCall,
  taskId: string,
  status: string,
  snapshot?: BackgroundTaskSnapshot,
): void {
  const taskType = runtimeTaskTypeForToolCall(toolCall);
  if (!taskType || !deps.runtimeTaskRegistry) return;
  deps.runtimeTaskRegistry.update(taskId, (current) => ({
    ...(isTerminalRuntimeTask(current)
      ? current
      : {
          ...current,
          completedAt: runtimeTaskCompletedAt(status, snapshot) ?? current.completedAt,
          description:
            runtimeTaskDescription(toolCall, undefined, snapshot) ?? current.description,
          error: runtimeTaskError(snapshot) ?? current.error,
          exitCode: runtimeTaskExitCode(snapshot) ?? current.exitCode,
          isBackgrounded: true,
          outputFile: backgroundTaskOutputMetadata(snapshot).outputFile ?? current.outputFile,
          pid: runtimeTaskPid(snapshot) ?? current.pid,
          // `?? current.resultText`: undefined Never clear the saved product (mid-running snapshot
          // The final state of the absence of products will come here).
          resultText: runtimeTaskResultText(toolCall, status, snapshot) ?? current.resultText,
          status: normalizeRuntimeTaskStatus(status),
          taskType,
          type: taskType,
        }),
  }));
}

/**
 * The artifact text of a workflow run. Taken only from the **terminal** snapshot of a dwf dispatch name
 * (CreateWorkflow / ResumeWorkflowRun): TaskOutput's projection can only read the registry entry (dwf never writes
 * outputFile), so an artifact that is not on the entry becomes completely unreachable after a restart.
 *
 * legacy `Workflow` deliberately takes no part — its result travels through `output.response` via the existing
 * notification path, and the contract is unchanged.
 */
function runtimeTaskResultText(
  toolCall: ExecutableToolCall,
  status: string,
  snapshot: BackgroundTaskSnapshot | undefined,
): string | undefined {
  if (!isDynamicWorkflowRunDispatchToolName(toolCall.name)) return undefined;
  if (status === "running") return undefined;
  if (!snapshot || !("output" in snapshot)) return undefined;
  return serializeWorkflowArtifact(snapshot.output);
}

export function claimRuntimeBackgroundTaskNotification(
  deps: ToolExecutorDeps,
  toolCall: ExecutableToolCall,
  taskId: string,
): boolean {
  if (!runtimeTaskTypeForToolCall(toolCall) || !deps.runtimeTaskRegistry) return true;
  let claimed = false;
  const task = deps.runtimeTaskRegistry.update(taskId, (current) => {
    if (current.notified) return current;
    claimed = true;
    return { ...current, notified: true };
  });
  return task === undefined ? true : claimed;
}

export function releaseRuntimeBackgroundTaskNotification(
  deps: ToolExecutorDeps,
  toolCall: ExecutableToolCall,
  taskId: string,
): void {
  if (!runtimeTaskTypeForToolCall(toolCall) || !deps.runtimeTaskRegistry) return;
  deps.runtimeTaskRegistry.update(taskId, (current) =>
    current.notified ? { ...current, notified: false } : current,
  );
}

export function removeRuntimeBackgroundTask(
  deps: ToolExecutorDeps,
  toolCall: ExecutableToolCall,
  taskId: string,
): void {
  if (!runtimeTaskTypeForToolCall(toolCall) || !deps.runtimeTaskRegistry) return;
  deps.runtimeTaskRegistry.remove(taskId);
}

function runtimeTaskTypeForToolCall(toolCall: ExecutableToolCall): RuntimeTaskType | undefined {
  switch (toolCall.name) {
    case "Bash":
      return "local_bash";
    case "Workflow":
      return "local_workflow";
    default:
      // The two entries of dwf (CreateWorkflow/ResumeWorkflowRun) share a taskType: if absent,
      // registerRuntimeBackgroundTask returns directly - the session recycling guardrail and TaskOutput visibility are lost.
      return isDynamicWorkflowRunDispatchToolName(toolCall.name)
        ? "local_dynamic_workflow"
        : undefined;
  }
}

function defaultRuntimeTaskDescription(taskType: RuntimeTaskType): string {
  switch (taskType) {
    case "local_bash":
      return "Bash background command";
    case "local_workflow":
      return "Workflow background task";
    case "local_dynamic_workflow":
      return "Dynamic workflow run";
    case "local_agent":
      return "Agent background task";
    case "monitor_mcp":
      return "Monitor background task";
  }
}

function normalizeRuntimeTaskStatus(status: string): RuntimeTaskSnapshot["status"] {
  switch (status) {
    case "running":
      return "running";
    case "completed":
      return "completed";
    case "cancelled":
    case "timed_out":
      return "killed";
    case "lost":
      return "lost";
    default:
      return "failed";
  }
}

function runtimeTaskDescription(
  toolCall: ExecutableToolCall,
  output?: Record<string, unknown>,
  snapshot?: BackgroundTaskSnapshot,
): string | undefined {
  const input = isRecord(toolCall.input) ? toolCall.input : {};
  if (snapshot && "description" in snapshot && typeof snapshot.description === "string") {
    return snapshot.description;
  }
  if (snapshot && "name" in snapshot && typeof snapshot.name === "string") return snapshot.name;
  if (output && typeof output.name === "string") return output.name;
  if (typeof input.description === "string") return input.description;
  if (typeof input.command === "string") return input.command;
  if (typeof input.name === "string") return input.name;
  if (typeof input.scriptPath === "string") return input.scriptPath;
  return undefined;
}

function runtimeTaskCompletedAt(
  status: string,
  snapshot: BackgroundTaskSnapshot | undefined,
): Date | undefined {
  if (status === "running") return undefined;
  return snapshot?.completedAt ?? new Date();
}

function runtimeTaskError(snapshot: BackgroundTaskSnapshot | undefined): string | undefined {
  if (!snapshot || !("error" in snapshot)) return undefined;
  const error = snapshot.error;
  return typeof error === "string" ? error : error?.message;
}

function runtimeTaskExitCode(snapshot: BackgroundTaskSnapshot | undefined): number | undefined {
  if (!snapshot || !("result" in snapshot)) return undefined;
  return snapshot.result?.exitCode;
}

function runtimeTaskPid(snapshot: BackgroundTaskSnapshot | undefined): number | undefined {
  if (!snapshot || !("pid" in snapshot)) return undefined;
  return snapshot.pid;
}
