import {
  SessionEventType,
  traceContextToLogContext,
  type BackgroundResultOriginMeta,
  type DynamicWorkflowRunError,
  type DynamicWorkflowRunStopReason,
  type ExecutionPort,
  type SessionEvent,
  type DynamicWorkflowRunSnapshot,
  type SubagentTaskSnapshot,
  type TraceContext,
  type TurnId,
  type WorkflowNotificationMeta,
  type WorkflowTaskSnapshot,
} from "@zcode/contracts";
import { isSubagentDispatchToolName } from "../compat.js";
import type { ExecutableToolCall } from "../types.js";
import type { ToolExecutorDeps } from "./types.js";
import { isRecord } from "./utils.js";
import { formatTaskNotification } from "../../runtime-task/notification.js";
import { describeWorkflowScriptPath } from "../handlers/workflow-script-path.js";
import {
  claimRuntimeBackgroundTaskNotification,
  isDynamicWorkflowRunDispatchToolName,
  registerRuntimeBackgroundTask,
  releaseRuntimeBackgroundTaskNotification,
  removeRuntimeBackgroundTask,
  updateRuntimeBackgroundTask,
} from "./background-task-registry.js";
import { backgroundTaskOutputMetadata } from "./background-task-output.js";
import {
  buildWorkflowReportsManifestSection,
  buildWorkflowReportsNotificationSection,
  serializeWorkflowArtifact,
} from "./workflow-artifact.js";
// ⚠ Two artifacts: The above one is the **top-level return value** of the script (`RunSettlement.artifact` inside the engine, enter
// `<result>`), the following is the output of the script released to the user via `artifact.*` (enter `<artifacts>`).
// The two appear side by side in the same completion notification, so the modules are also separated.
import {
  buildWorkflowArtifactsManifestSection,
  buildWorkflowArtifactsNotificationSection,
  toPublishedArtifactSummaries,
  WORKFLOW_ARTIFACTS_NOTIFICATION_MAX_LINES,
} from "./workflow-published-artifacts.js";

type BackgroundTaskSnapshot =
  | NonNullable<Awaited<ReturnType<NonNullable<ExecutionPort["getBackgroundTask"]>>>>
  | SubagentTaskSnapshot
  | WorkflowTaskSnapshot
  // The snapshot of workflow run follows the shape of WorkflowTaskSnapshot but relaxes the output to unknown (the product is generated by the script
  // Determined by the top-level return value), so it is not a subtype of WorkflowTaskSnapshot and must be listed separately.
  | DynamicWorkflowRunSnapshot;

type BackgroundTaskWaiter = {
  waitForBackgroundTask(
    taskId: string,
    options?: { signal?: AbortSignal },
  ): Promise<BackgroundTaskSnapshot | undefined>;
};

type WorkflowTaskWaiter = {
  waitForTask(
    taskId: string,
    options?: { signal?: AbortSignal },
  ): Promise<BackgroundTaskSnapshot | undefined>;
};

/**
 * A tool's background lifecycle provider. If these five things are scattered in five places according to the tool name `if (toolCall.name === ...)`,
 * Every time you connect a background tool, you must remember to change five things at the same time - `canCancelBackgroundTask` versus legacy `Workflow`
 * Hardly returning false will be the scene of missing changes: it will make the "cancellable" of the started payload always false, and it will die directly if the entry is cancelled.
 * Look up the table by the object name to get this structure, and allocate five parts to degenerate into reading its fields.
 *
 * The default semantics (field absence) are the same verbatim as before generalization: no getSnapshot → no snapshot provider (cannot afford 1s polling);
 * None waitForTerminal → No direct waiter; cancelable defaults to false.
 */
interface BackgroundTaskLifecycleProvider {
  /** Snapshot source for 1s polling. */
  getSnapshot?: (taskId: string) => Promise<BackgroundTaskSnapshot | undefined>;
  /** Final state direct waiter (more timely than polling, and the only source of final state when the polling source is absent). */
  waitForTerminal?: (taskId: string) => Promise<BackgroundTaskSnapshot | undefined>;
  /** Whether the running task can be canceled by the user; determines the `cancellable` of the started/updated payload. */
  cancellable?: boolean;
}

export class BackgroundTaskTracker {
  private readonly backgroundPollers = new Set<string>();

  constructor(private readonly deps: ToolExecutorDeps) {}

  async trackBackgroundTask(
    toolCall: ExecutableToolCall,
    output: unknown,
    traceContext: TraceContext,
    turnId: TurnId | undefined,
  ): Promise<void> {
    if (!isRecord(output)) return;
    if (!isBackgroundTaskLaunch(toolCall, output)) return;
    const taskId =
      typeof output.backgroundTaskId === "string"
        ? output.backgroundTaskId
        : typeof output.agentId === "string"
          ? output.agentId
          : undefined;
    if (!taskId || this.backgroundPollers.has(taskId)) return;

    this.backgroundPollers.add(taskId);
    registerRuntimeBackgroundTask(this.deps, toolCall, taskId, output, turnId);
    try {
      await this.emitBackgroundTaskEvent(
        SessionEventType.BackgroundTaskStarted,
        this.backgroundTaskPayload(toolCall, taskId, "running", undefined, output),
        traceContext,
        turnId,
      );
    } catch (error) {
      this.backgroundPollers.delete(taskId);
      removeRuntimeBackgroundTask(this.deps, toolCall, taskId);
      throw error;
    }

    const hasSnapshotProvider = this.hasBackgroundTaskSnapshotProvider(toolCall);
    const hasDirectWaiter = this.hasDirectBackgroundTaskWaiter(toolCall);
    this.deps.logger?.info?.("Background task tracking started", {
      ...traceContextToLogContext(traceContext),
      event: "background_task.tracking.started",
      hasDirectWaiter,
      hasSnapshotProvider,
      module: "core.tool.executor",
      taskId,
      toolName: toolCall.name,
    });

    if (!hasSnapshotProvider && !hasDirectWaiter) {
      this.deps.logger?.info?.("Background task tracking lost without snapshot source", {
        ...traceContextToLogContext(traceContext),
        event: "background_task.tracking.lost",
        module: "core.tool.executor",
        reason: "missing_snapshot_source",
        taskId,
        toolName: toolCall.name,
      });
      updateRuntimeBackgroundTask(this.deps, toolCall, taskId, "lost");
      this.maybeEnqueueBackgroundTaskNotification(
        toolCall,
        taskId,
        "lost",
        undefined,
        traceContext,
        output,
      );
      await this.emitBackgroundTaskEvent(
        SessionEventType.BackgroundTaskCompleted,
        this.backgroundTaskPayload(toolCall, taskId, "lost", undefined, output),
        traceContext,
        turnId,
      );
      this.backgroundPollers.delete(taskId);
      return;
    }

    let lastSnapshotSignature = "";
    let completing = false;
    let polling = false;
    let stopped = false;
    let timer: ReturnType<typeof setInterval> | undefined;
    let maxRuntimeTimer: ReturnType<typeof setTimeout> | undefined;

    const stopTracking = () => {
      if (timer) clearInterval(timer);
      timer = undefined;
      if (maxRuntimeTimer) clearTimeout(maxRuntimeTimer);
      maxRuntimeTimer = undefined;
      this.backgroundPollers.delete(taskId);
    };

    if (
      toolCall.name === "Bash" &&
      this.deps.runtimeScope === "subagent" &&
      this.deps.subagentBackgroundBashMaxMs !== undefined &&
      this.deps.executionPort?.cancelBackgroundTask
    ) {
      maxRuntimeTimer = setTimeout(() => {
        this.deps.logger?.warn("Subagent background Bash exceeded max runtime; cancelling", {
          ...traceContextToLogContext(traceContext),
          event: "background_task.subagent_bash.max_runtime_exceeded",
          module: "core.tool.executor",
          taskId,
          toolName: toolCall.name,
        });
        void Promise.resolve(this.deps.executionPort?.cancelBackgroundTask?.(taskId)).catch(
          (error) => {
            this.deps.logger?.warn("Subagent background Bash cancellation failed", {
              ...traceContextToLogContext(traceContext),
              errorMessage: error instanceof Error ? error.message : String(error),
              event: "background_task.subagent_bash.cancel_failed",
              module: "core.tool.executor",
              taskId,
              toolName: toolCall.name,
            });
          },
        );
      }, this.deps.subagentBackgroundBashMaxMs);
    }

    const emitRunningUpdate = async (snapshot: BackgroundTaskSnapshot) => {
      const signature = this.backgroundSnapshotSignature(snapshot);
      if (signature === lastSnapshotSignature) return;
      lastSnapshotSignature = signature;
      updateRuntimeBackgroundTask(this.deps, toolCall, taskId, "running", snapshot);
      await this.emitBackgroundTaskEvent(
        SessionEventType.BackgroundTaskUpdated,
        this.backgroundTaskPayload(toolCall, taskId, "running", snapshot, output),
        traceContext,
        turnId,
      );
    };

    const emitTerminalSnapshot = async (
      snapshot: BackgroundTaskSnapshot | undefined,
    ): Promise<void> => {
      if (stopped || completing) return;
      completing = true;
      try {
        if (!snapshot) {
          this.deps.logger?.info?.("Background task terminal snapshot missing", {
            ...traceContextToLogContext(traceContext),
            event: "background_task.tracking.lost",
            module: "core.tool.executor",
            reason: "snapshot_missing",
            taskId,
            toolName: toolCall.name,
          });
          updateRuntimeBackgroundTask(this.deps, toolCall, taskId, "lost");
          this.maybeEnqueueBackgroundTaskNotification(
            toolCall,
            taskId,
            "lost",
            undefined,
            traceContext,
            output,
          );
          await this.emitBackgroundTaskEvent(
            SessionEventType.BackgroundTaskCompleted,
            this.backgroundTaskPayload(toolCall, taskId, "lost", undefined, output),
            traceContext,
            turnId,
          );
          stopped = true;
          stopTracking();
          return;
        }

        if (snapshot.status === "running") {
          updateRuntimeBackgroundTask(this.deps, toolCall, taskId, "running", snapshot);
          await emitRunningUpdate(snapshot);
          if (!hasSnapshotProvider) {
            stopped = true;
            stopTracking();
          }
          return;
        }

        if (this.isNotifiedLocalAgentSnapshot(toolCall, snapshot)) {
          this.deps.logger?.debug?.(
            "Background task terminal notification already handled by subagent",
            {
              ...traceContextToLogContext(traceContext),
              event: "background_task.tracking.notification_already_handled",
              module: "core.tool.executor",
              taskId,
              toolName: toolCall.name,
            },
          );
          stopped = true;
          stopTracking();
          return;
        }

        this.deps.logger?.info?.("Background task terminal snapshot observed", {
          ...traceContextToLogContext(traceContext),
          event: "background_task.tracking.terminal",
          module: "core.tool.executor",
          taskId,
          taskStatus: snapshot.status,
          toolName: toolCall.name,
        });
        updateRuntimeBackgroundTask(this.deps, toolCall, taskId, snapshot.status, snapshot);
        this.maybeEnqueueBackgroundTaskNotification(
          toolCall,
          taskId,
          snapshot.status,
          snapshot,
          traceContext,
        );
        await this.emitBackgroundTaskEvent(
          SessionEventType.BackgroundTaskCompleted,
          this.backgroundTaskPayload(toolCall, taskId, snapshot.status, snapshot, output),
          traceContext,
          turnId,
        );
        stopped = true;
        stopTracking();
      } finally {
        completing = false;
      }
    };

    const poll = async () => {
      if (polling || stopped || !hasSnapshotProvider) return;
      polling = true;
      try {
        const snapshot = await this.getBackgroundTaskSnapshot(toolCall, taskId);
        if (!snapshot) {
          await emitTerminalSnapshot(undefined);
          return;
        }

        if (snapshot.status === "running") {
          await emitRunningUpdate(snapshot);
          return;
        }

        await emitTerminalSnapshot(snapshot);
      } catch (error) {
        this.deps.logger?.warn("Background task polling failed", {
          ...traceContextToLogContext(traceContext),
          errorMessage: error instanceof Error ? error.message : String(error),
          module: "core.tool.executor",
          taskId,
        });
      } finally {
        polling = false;
      }
    };

    const waitForCompletion = async () => {
      try {
        const snapshot = await this.waitForBackgroundTaskSnapshot(toolCall, taskId);
        await emitTerminalSnapshot(snapshot);
      } catch (error) {
        this.deps.logger?.warn("Background task wait failed", {
          ...traceContextToLogContext(traceContext),
          errorMessage: error instanceof Error ? error.message : String(error),
          module: "core.tool.executor",
          taskId,
        });
        if (!hasSnapshotProvider) {
          stopped = true;
          stopTracking();
        }
      }
    };

    if (hasSnapshotProvider) {
      timer = setInterval(() => {
        void poll();
      }, 1_000);
      timer.unref?.();
      await poll();
    }

    if (hasDirectWaiter && !stopped) {
      void waitForCompletion();
    }
  }

  private async emitBackgroundTaskEvent(
    type: SessionEvent["type"],
    payload: Record<string, unknown>,
    traceContext: TraceContext,
    turnId: TurnId | undefined,
  ): Promise<void> {
    await this.deps.emitEvent({
      id: crypto.randomUUID() as any,
      sessionId: this.deps.sessionId,
      turnId,
      type,
      timestamp: new Date(),
      traceId: traceContext.traceId,
      sequenceNumber: 0,
      payload,
    });
  }

  private backgroundTaskPayload(
    toolCall: ExecutableToolCall,
    taskId: string,
    status: string,
    snapshot?: BackgroundTaskSnapshot,
    output?: Record<string, unknown>,
  ): Record<string, unknown> {
    const input = isRecord(toolCall.input) ? toolCall.input : {};
    const outputMetadata = backgroundTaskOutputMetadata(snapshot, output);

    return {
      taskId,
      toolCallId: toolCall.id,
      toolName: toolCall.name,
      // V4 projection used to infer the type from toolName handwriting, missing the real Agent
      // After the tool name, cast the background subagent to bash/process. The runtime is adjudicated once at the occurrence of the fact.
      // Lifecycle behavior is not affected - that is already dispatched by the per-tool lifecycleProvider.
      taskKind: backgroundTaskKind(toolCall.name),
      childSessionId: outputMetadata.childSessionId,
      cancellable: status === "running" && this.canCancelBackgroundTask(toolCall),
      command: typeof input.command === "string" ? input.command : undefined,
      // There is no `description` in the input schema of CreateWorkflow (only `{name?, script}`,
      // contracts/src/tools/create-workflow.ts), take the general input.description → snapshot.description
      // The entire link field is absent, so the title of the Workflows partition is returned to toolName, and each run is displayed as
      // "CreateWorkflow". The display name and completion notification share the same backend chain (including input.name), so they can be reused directly.
      // workflowTaskSubject. The last link is taskId (≡ runId): the projection will treat it as the title as it is, and when it is absent,
      // Fallback toolName is not the same - the UI side agrees that title ≡ workId is treated as "unnamed" and fallbackName is used instead.
      // Therefore, this link cannot be seen by the user, while maintaining the simplicity of "description is never empty".
      // The dwf dispatch name is expanded to ResumeWorkflowRun: the same backend chain (it also only has run_id, no description).
      description: isDynamicWorkflowRunDispatchToolName(toolCall.name)
        ? workflowTaskSubject(toolCall, taskId, snapshot, output)
        : typeof input.description === "string"
          ? input.description
          : snapshot && "description" in snapshot
            ? snapshot.description
            : undefined,
      status,
      pid: snapshot && "pid" in snapshot ? snapshot.pid : undefined,
      startedAt: snapshot?.startedAt,
      completedAt: snapshot?.completedAt,
      outputPath: outputMetadata.outputFile,
      stderrPersistedOutputPath: outputMetadata.stderrFile,
      stdoutPersistedOutputPath: outputMetadata.stdoutFile,
      outputBytes: outputMetadata.outputBytes,
      outputTruncated: outputMetadata.outputTruncated,
      outputTail: outputMetadata.outputTail,
      stderrBytes: outputMetadata.stderrBytes,
      stderrTail: outputMetadata.stderrTail,
      stdoutBytes: outputMetadata.stdoutBytes,
      stdoutTail: outputMetadata.stdoutTail,
      terminalId: taskId,
    };
  }

  private backgroundSnapshotSignature(snapshot: BackgroundTaskSnapshot): string {
    return JSON.stringify({
      pid: snapshot && "pid" in snapshot ? snapshot.pid : undefined,
      stderrBytes: snapshot && "stderrBytes" in snapshot ? snapshot.stderrBytes : undefined,
      stderrTail: snapshot && "stderrTail" in snapshot ? snapshot.stderrTail : undefined,
      stdoutBytes: snapshot && "stdoutBytes" in snapshot ? snapshot.stdoutBytes : undefined,
      stdoutTail: snapshot && "stdoutTail" in snapshot ? snapshot.stdoutTail : undefined,
    });
  }

  private canCancelBackgroundTask(toolCall: ExecutableToolCall): boolean {
    return this.lifecycleProvider(toolCall).cancellable === true;
  }

  private isNotifiedLocalAgentSnapshot(
    toolCall: ExecutableToolCall,
    snapshot: BackgroundTaskSnapshot,
  ): boolean {
    const record = snapshot as unknown as Record<string, unknown>;
    return (
      isSubagentDispatchToolName(toolCall.name) &&
      record.type === "local_agent" &&
      record.notified === true
    );
  }

  private maybeEnqueueBackgroundTaskNotification(
    toolCall: ExecutableToolCall,
    taskId: string,
    status: string,
    snapshot: BackgroundTaskSnapshot | undefined,
    traceContext: TraceContext,
    output?: Record<string, unknown>,
  ): void {
    if (!this.deps.enqueueBackgroundTaskNotification) {
      this.deps.logger?.debug?.("Background task notification queue unavailable", {
        ...traceContextToLogContext(traceContext),
        event: "background_task.notification.queue_unavailable",
        module: "core.tool.executor",
        taskId,
        taskStatus: status,
        toolName: toolCall.name,
      });
      return;
    }

    // The run superseded by the revision does not send final notification:
    // The result of the AmendWorkflow tool when it was stopped is the model's response to that stop.
    // All we know is that another line of "you stopped run A, now revise it" will send the model into the loop. still claim: let later
    // TaskOutput reads do not treat this as an undelivered notification.
    if (workflowSnapshotTerminal(status, snapshot)?.stopReason === "superseded") {
      claimRuntimeBackgroundTaskNotification(this.deps, toolCall, taskId);
      this.deps.logger?.info?.("Background task notification suppressed: run superseded", {
        ...traceContextToLogContext(traceContext),
        event: "background_task.notification.suppressed",
        module: "core.tool.executor",
        reason: "workflow_run_superseded",
        taskId,
        taskStatus: status,
        toolName: toolCall.name,
      });
      return;
    }

    if (
      this.deps.shouldEnqueueBackgroundTaskNotification?.({
        runtimeScope: this.deps.runtimeScope,
        status,
        taskId,
        toolName: toolCall.name,
        traceContext,
      }) === false
    ) {
      this.deps.logger?.info?.("Background task notification suppressed by runtime policy", {
        ...traceContextToLogContext(traceContext),
        event: "background_task.notification.suppressed",
        module: "core.tool.executor",
        taskId,
        taskStatus: status,
        toolName: toolCall.name,
      });
      return;
    }

    const text = this.formatBackgroundTaskNotification(toolCall, taskId, status, snapshot, output);
    if (!text) {
      this.deps.logger?.debug?.("Background task notification skipped without formatted message", {
        ...traceContextToLogContext(traceContext),
        event: "background_task.notification.skipped",
        module: "core.tool.executor",
        reason: "empty_message",
        taskId,
        taskStatus: status,
        toolName: toolCall.name,
      });
      return;
    }
    // When TaskOutput reads the final state, it will first mark the same registry task as notified;
    // Completion can only be added to the queue after a successful claim, preventing the model from receiving tool result and duplicate notifications at the same time.
    if (!claimRuntimeBackgroundTaskNotification(this.deps, toolCall, taskId)) {
      this.deps.logger?.debug?.("Background task notification already claimed", {
        ...traceContextToLogContext(traceContext),
        event: "background_task.tracking.notification_already_handled",
        module: "core.tool.executor",
        taskId,
        taskStatus: status,
        toolName: toolCall.name,
      });
      return;
    }
    try {
      this.deps.enqueueBackgroundTaskNotification({
        ...(toolCall.name === "Bash"
          ? {
              originMeta: {
                backgroundSource: "bash" as const,
                title: resolveBashBackgroundResultTitle(toolCall, taskId),
                workId: taskId,
              },
            }
          : {}),
        // The final round of workflow run should be rendered as a background result header instead of degenerating into a bare model-only message.
        // So originMeta must bring (workId ≡ runId). CreateWorkflow and ResumeWorkflowRun
        // The two entries are isomorphic (see isDynamicWorkflowRunDispatchToolName for dispatch). manifest payload
        // (workflowNotification) Fire side casting here: the only data source for GUI rendering, fully pipelined with originMeta.
        ...(isDynamicWorkflowRunDispatchToolName(toolCall.name)
          ? {
              originMeta: buildWorkflowNotificationOriginMeta(
                toolCall,
                taskId,
                status,
                snapshot,
                output,
              ),
            }
          : {}),
        taskId,
        text,
        toolName: toolCall.name,
        traceContext,
      });
    } catch (error) {
      releaseRuntimeBackgroundTaskNotification(this.deps, toolCall, taskId);
      this.deps.logger?.warn("Background task notification enqueue failed", {
        ...traceContextToLogContext(traceContext),
        errorMessage: error instanceof Error ? error.message : String(error),
        module: "core.tool.executor",
        taskId,
      });
      return;
    }
    this.deps.logger?.info?.("Background task notification enqueued", {
      ...traceContextToLogContext(traceContext),
      event: "background_task.notification.enqueued",
      module: "core.tool.executor",
      taskId,
      taskStatus: status,
      toolName: toolCall.name,
    });
  }

  private formatBackgroundTaskNotification(
    toolCall: ExecutableToolCall,
    taskId: string,
    status: string,
    snapshot: BackgroundTaskSnapshot | undefined,
    output?: Record<string, unknown>,
  ): string | undefined {
    // workflow run reuses the notification format of legacy Workflow (reuses formatWorkflowTaskNotification).
    // legacy "Workflow" remains independent: it does not have the product/reports semantics of dwf, only in the shared formatter
    // Take your own output.response fallback branch.
    if (toolCall.name === "Workflow" || isDynamicWorkflowRunDispatchToolName(toolCall.name)) {
      return this.formatWorkflowTaskNotification(toolCall, taskId, status, snapshot, output);
    }
    if (toolCall.name !== "Bash") return undefined;

    const input = isRecord(toolCall.input) ? toolCall.input : {};
    const command = typeof input.command === "string" ? input.command : undefined;
    const description = typeof input.description === "string" ? input.description : undefined;
    const result = snapshot && "result" in snapshot ? snapshot.result : undefined;
    const outputMetadata = backgroundTaskOutputMetadata(snapshot, output);
    const notificationStatus = normalizeBashTaskNotificationStatus(status);
    const summary = buildBackgroundTaskSummary({
      command,
      description,
      exitCode: result?.exitCode,
      lost: status === "lost",
      status: notificationStatus,
    });
    return formatTaskNotification({
      description,
      outputFile: outputMetadata.outputFile,
      status: notificationStatus,
      summary,
      taskId,
      taskType: "local_bash",
      toolUseId: toolCall.id,
    });
  }

  private formatWorkflowTaskNotification(
    toolCall: ExecutableToolCall,
    taskId: string,
    status: string,
    snapshot: BackgroundTaskSnapshot | undefined,
    launchOutput?: Record<string, unknown>,
  ): string {
    const output =
      snapshot && "output" in snapshot && isRecord(snapshot.output)
        ? snapshot.output
        : launchOutput;
    const subject = workflowTaskSubject(toolCall, taskId, snapshot, output);
    const notificationStatus = normalizeBackgroundTaskNotificationStatus(status);
    // The three final words and stop reasons of dwf are read from the snapshot: run service
    // `stopReason` in journal is projected to `snapshot.stopReason`, so "who stopped" no longer only lives in the registry.
    // The stopInitiator of the registry is only for compatibility (when the old port/stub does not send stopReason).
    const terminal = workflowSnapshotTerminal(status, snapshot);
    const stopReason =
      terminal?.stopReason ??
      (status === "cancelled"
        ? this.deps.runtimeTaskRegistry?.get(taskId)?.stopInitiator
        : undefined);
    const summary = buildWorkflowTaskSummary({
      lost: status === "lost",
      status: notificationStatus,
      runStatus: terminal?.runStatus,
      stopReason,
      subject,
    });
    // dwf and legacy `Workflow` differ on the **result** item:
    //   - The product of dwf is any top-level return value of the script. Take the original value of `snapshot.output` and serialize it uniformly, and **never**
    //     Fallback to launch output - the latter's `response` is the archaic prose of "run has started in the background",
    //     Falling back into the past is worse than absence (the second manifestation of desktop bugs).
    //   - `output.response` of legacy `Workflow` really exists, launchOutput fallback is its own contract,
    //     Reserved byte by byte.
    // The subject still goes to the output of the record gate above (the display name does not involve the product shape).
    // The dwf dispatch name is expanded to ResumeWorkflowRun: the resumed run and the newly started run are isomorphic in notification shape.
    const result = isDynamicWorkflowRunDispatchToolName(toolCall.name)
      ? serializeWorkflowArtifact(snapshot && "output" in snapshot ? snapshot.output : undefined)
      : stringField(output, "response");
    // Progressive artifacts (`report(item)`) belong only to dwf: legacy `Workflow` does not have this concept, and its notifications are unchanged byte by byte.
    // **All three final states are carried** (completed / failed / canceled): a run that died on the 12th ask
    // After completing 11 ask tasks, just reporting "failed" is equivalent to throwing it all away - that is the reason for the existence of report.
    // The entries come from the kind="report" line of the journal (which the run service puts on the snapshot), not the memory-only projection.
    const isDynamicWorkflow = isDynamicWorkflowRunDispatchToolName(toolCall.name);
    const reports = isDynamicWorkflow
      ? buildWorkflowReportsNotificationSection(workflowSnapshotReports(snapshot))
      : undefined;
    // User plane products also only belong to dwf (legacy `Workflow` does not have this concept, and the notification remains unchanged byte by byte). three final states
    // Always carry: the released product of a failed run is still in front of the user, the notification does not mention it, and the model will be repeated.
    const artifacts = isDynamicWorkflow
      ? buildWorkflowArtifactsNotificationSection(
          workflowSnapshotArtifacts(snapshot),
          WORKFLOW_ARTIFACTS_NOTIFICATION_MAX_LINES,
        )
      : undefined;
    // Script files also belong only to dwf: the rendering guide relies on it to
    // The next step is to "edit that file in place". The journal is stored in an absolute path, and the model side is written relative to the workspace——
    // It next edits the file, and that's exactly the kind of path it uses when reading and writing files elsewhere.
    const scriptPath = isDynamicWorkflow ? workflowSnapshotScriptPath(snapshot) : undefined;
    return formatTaskNotification({
      description: subject,
      // Deliverable rendering guidelines are also DWF-only.
      ...(isDynamicWorkflow ? { deliveryGuidance: true } : {}),
      ...(scriptPath === undefined
        ? {}
        : { scriptPath: describeWorkflowScriptPath(scriptPath, this.deps.getWorkingDirectory()) }),
      error: snapshot && "error" in snapshot ? runtimeString(snapshot.error) : undefined,
      ...(reports === undefined ? {} : { reports }),
      ...(artifacts === undefined ? {} : { artifacts }),
      result,
      status: notificationStatus,
      ...(terminal?.runStatus === undefined ? {} : { runStatus: terminal.runStatus }),
      ...(stopReason === undefined ? {} : { stopReason }),
      ...(terminal?.failure === undefined ? {} : { failure: terminal.failure }),
      summary,
      taskId,
      taskType: "local_workflow",
      toolUseId: toolCall.id,
    });
  }

  private hasBackgroundTaskSnapshotProvider(toolCall: ExecutableToolCall): boolean {
    return this.lifecycleProvider(toolCall).getSnapshot !== undefined;
  }

  private hasDirectBackgroundTaskWaiter(toolCall: ExecutableToolCall): boolean {
    return this.lifecycleProvider(toolCall).waitForTerminal !== undefined;
  }

  private async waitForBackgroundTaskSnapshot(
    toolCall: ExecutableToolCall,
    taskId: string,
  ): Promise<BackgroundTaskSnapshot | undefined> {
    return this.lifecycleProvider(toolCall).waitForTerminal?.(taskId);
  }

  private async getBackgroundTaskSnapshot(
    toolCall: ExecutableToolCall,
    taskId: string,
  ): Promise<BackgroundTaskSnapshot | undefined> {
    return this.lifecycleProvider(toolCall).getSnapshot?.(taskId);
  }

  /**
   * Resolve background lifecycle providers by tool name. Each branch only describes "which port is responsible for the four things of this tool",
   * Corresponds one-to-one with the five ifs before generalization, and the semantics are maintained verbatim.
   */
  private lifecycleProvider(toolCall: ExecutableToolCall): BackgroundTaskLifecycleProvider {
    const deps = this.deps;

    if (isSubagentDispatchToolName(toolCall.name)) {
      const getTask = deps.subagentPort?.getTask;
      return {
        ...(getTask
          ? { getSnapshot: (taskId: string) => getTask.call(deps.subagentPort, taskId) }
          : {}),
        // The stop entry of background Agent is subagentPort.stopTask;
        // Started payload cannot be judged by Bash's executionPort capability.
        cancellable: Boolean(deps.subagentPort?.stopTask),
      };
    }

    if (isDynamicWorkflowRunDispatchToolName(toolCall.name)) {
      // workflow run: snapshot/wait/cancel all from narrow port DynamicWorkflowRunPort (runId ≡ taskId ≡ workId).
      // The ability to cancel is subject to the existence of the cancel method, rather than hard-coding - the port can be canceled if it is present, which is exactly what the details page
      // The premise of the only path shared by the Cancel button and the background panel. CreateWorkflow (new start) with
      // ResumeWorkflowRun (resume) shares the same provider: registry entry heavy arm merged with existing
      // The semantics follows the parentToolCallId of the original tool line, and the two entries are completely isomorphic to the tracker.
      const port = deps.dynamicWorkflowRunPort;
      if (port === undefined) return {};
      return {
        getSnapshot: (taskId: string) => port.getTask(taskId),
        ...(typeof port.waitForTask === "function"
          ? { waitForTerminal: (taskId: string) => port.waitForTask(taskId) }
          : {}),
        cancellable: typeof port.cancel === "function",
      };
    }

    if (toolCall.name === "Workflow") {
      // legacy Workflow: only snapshots and waiting, no cancellation - the stop entry is never taken (keep false before generalization).
      const getTask = deps.workflowPort?.getTask;
      const waiter = getWorkflowTaskWaiter(deps.workflowPort);
      return {
        ...(getTask
          ? { getSnapshot: (taskId: string) => getTask.call(deps.workflowPort, taskId) }
          : {}),
        ...(waiter ? { waitForTerminal: (taskId: string) => waiter.waitForTask(taskId) } : {}),
        cancellable: false,
      };
    }

    if (toolCall.name === "Bash") {
      const waiter = getBackgroundTaskWaiter(deps.executionPort);
      const getBackgroundTask = deps.executionPort?.getBackgroundTask;
      return {
        ...(getBackgroundTask
          ? { getSnapshot: (taskId: string) => getBackgroundTask.call(deps.executionPort, taskId) }
          : {}),
        ...(waiter
          ? { waitForTerminal: (taskId: string) => waiter.waitForBackgroundTask(taskId) }
          : {}),
        cancellable: Boolean(deps.executionPort?.cancelBackgroundTask),
      };
    }

    // The rest of the tools follow the common backend of executionPort (no direct waiters), which is the same as before generalization.
    const getBackgroundTask = deps.executionPort?.getBackgroundTask;
    return {
      ...(getBackgroundTask
        ? { getSnapshot: (taskId: string) => getBackgroundTask.call(deps.executionPort, taskId) }
        : {}),
      cancellable: Boolean(deps.executionPort?.cancelBackgroundTask),
    };
  }
}

function isBackgroundTaskLaunch(
  toolCall: ExecutableToolCall,
  output: Record<string, unknown>,
): boolean {
  if (output.status === "backgrounded") return true;
  return isSubagentDispatchToolName(toolCall.name) && output.status === "async_launched";
}

type BashTaskNotificationStatus = "completed" | "failed" | "killed";

function normalizeBashTaskNotificationStatus(status: string): BashTaskNotificationStatus {
  return normalizeBackgroundTaskNotificationStatus(status);
}

function normalizeBackgroundTaskNotificationStatus(status: string): BashTaskNotificationStatus {
  switch (status) {
    case "completed":
      return "completed";
    case "cancelled":
    case "timed_out":
    case "killed":
    case "stopped":
      return "killed";
    default:
      return "failed";
  }
}

function resolveBashBackgroundResultTitle(toolCall: ExecutableToolCall, taskId: string): string {
  const input = isRecord(toolCall.input) ? toolCall.input : {};
  const description = stringField(input, "description")?.trim();
  const command = stringField(input, "command")?.trim();
  return description || command || toolCall.name || taskId;
}

function buildBackgroundTaskSummary(input: {
  command?: string;
  description?: string;
  exitCode?: number;
  lost?: boolean;
  status: BashTaskNotificationStatus;
}): string {
  const subject = input.description ?? input.command ?? "Bash background command";
  const prefix = `Background command "${subject}"`;
  // Provider-visible summary keeps it simple; the full output path is carried by the output-file field of task-notification.
  if (input.lost) return `${prefix} failed because its in-process state was lost`;
  switch (input.status) {
    case "completed":
      return `${prefix} completed${input.exitCode !== undefined ? ` (exit code ${input.exitCode})` : ""}`;
    case "failed":
      return `${prefix} failed${input.exitCode !== undefined ? ` with exit code ${input.exitCode}` : ""}`;
    case "killed":
      return `${prefix} was stopped`;
  }
}

function buildWorkflowTaskSummary(input: {
  lost?: boolean;
  status: BashTaskNotificationStatus;
  runStatus?: WorkflowTerminalRunStatus;
  stopReason?: DynamicWorkflowRunStopReason | undefined;
  subject: string;
}): string {
  const prefix = `Workflow "${input.subject}"`;
  if (input.lost) return `${prefix} failed because its in-process state was lost.`;
  // One sentence should explain "how it ends": the model reads the summary earlier than the XML field. The third final state word of dwf takes precedence;
  // legacy `Workflow` without runStatus, falls back to generic word for tracker.
  if (input.runStatus === "errored") return `${prefix} errored: the script failed.`;
  if (input.runStatus === "stopped" || input.status === "killed") {
    switch (input.stopReason) {
      case "user":
        return `${prefix} was stopped by the user.`;
      case "model":
        return `${prefix} was stopped by you (TaskStop).`;
      case "provider":
        return `${prefix} was stopped on a provider error.`;
      case "interrupted":
        return `${prefix} was stopped: the process that owned it exited.`;
      case "superseded":
        return `${prefix} was stopped and superseded by an amended run.`;
      default:
        return `${prefix} was stopped.`;
    }
  }
  return input.status === "completed" ? `${prefix} completed.` : `${prefix} failed.`;
}

type WorkflowTerminalRunStatus = "completed" | "errored" | "stopped";

/**
 * Three final state facts on dwf snapshot. Only the dwf snapshot tape
 * `runStatus` / `stopReason` / `failure` (port contract `DynamicWorkflowRunSnapshot`); old port or
 * When stub does not send them, it is converted according to the common word of the tracker: `failed` → errored, `cancelled` → stopped (reason is absent,
 * It is up to the caller to get the details of the registry). Non-final state returns undefined.
 */
function workflowSnapshotTerminal(
  status: string,
  snapshot: BackgroundTaskSnapshot | undefined,
):
  | {
      runStatus: WorkflowTerminalRunStatus;
      stopReason?: DynamicWorkflowRunStopReason;
      failure?: DynamicWorkflowRunError;
    }
  | undefined {
  const record = snapshot === undefined ? undefined : (snapshot as Record<string, unknown>);
  const declared = record?.runStatus;
  const runStatus: WorkflowTerminalRunStatus | undefined =
    declared === "completed" || declared === "errored" || declared === "stopped"
      ? declared
      : status === "completed"
        ? "completed"
        : status === "failed"
          ? "errored"
          : status === "cancelled"
            ? "stopped"
            : undefined;
  if (runStatus === undefined) return undefined;
  const reason = record?.stopReason;
  const stopReason =
    runStatus === "stopped" &&
    (reason === "user" ||
      reason === "model" ||
      reason === "provider" ||
      reason === "interrupted" ||
      reason === "superseded")
      ? reason
      : undefined;
  const failure = isRecord(record?.failure)
    ? (record?.failure as unknown as DynamicWorkflowRunError)
    : undefined;
  return {
    runStatus,
    ...(stopReason === undefined ? {} : { stopReason }),
    ...(failure === undefined ? {} : { failure }),
  };
}

function workflowTaskSubject(
  toolCall: ExecutableToolCall,
  taskId: string,
  snapshot: BackgroundTaskSnapshot | undefined,
  output: Record<string, unknown> | undefined,
): string {
  const input = isRecord(toolCall.input) ? toolCall.input : {};
  return (
    stringField(input, "description") ??
    (snapshot && "description" in snapshot ? runtimeString(snapshot.description) : undefined) ??
    (snapshot && "name" in snapshot ? runtimeString(snapshot.name) : undefined) ??
    stringField(output, "name") ??
    stringField(input, "name") ??
    stringField(input, "scriptPath") ??
    taskId
  );
}

function runtimeString(value: unknown): string | undefined {
  return typeof value === "string" ? value : undefined;
}

/** The boundaries of each field in the manifest payload (`WorkflowNotificationMeta`). The launch side is cut off in place - the payload changes with turnHeader
 *  row adopts protocol + snapshot, shared `workflowNotificationMetaSchema` uses the same group of `.max()` to check,
 *  Out of bounds will cause zod to reject the entire row when it is dropped into the library. Therefore, truncation is the rule before **structuring, not an optional ending. */
const WORKFLOW_NOTIFICATION_SUMMARY_MAX_CHARS = 500;
const WORKFLOW_NOTIFICATION_RESULT_MAX_CHARS = 4_000;
const WORKFLOW_NOTIFICATION_ERROR_MAX_CHARS = 2_000;

/**
 * workflow originMeta of workflow run final notification (including manifest payload). CreateWorkflow/ResumeWorkflowRun
 * The two entrances are isomorphic and are both cast here: title and summary have the same origin (`workflowTaskSubject`), and the load is only in the final state and
 * Snapshot is carried when present** (non-final state/lost no snapshot → whole field is absent, GUI returns to bare header row).
 */
function buildWorkflowNotificationOriginMeta(
  toolCall: ExecutableToolCall,
  taskId: string,
  status: string,
  snapshot: BackgroundTaskSnapshot | undefined,
  output: Record<string, unknown> | undefined,
): BackgroundResultOriginMeta {
  const subject = workflowTaskSubject(toolCall, taskId, snapshot, output);
  const workflowNotification = buildWorkflowTerminalNotification(status, subject, snapshot);
  return {
    backgroundSource: "workflow",
    title: subject,
    workId: taskId,
    ...(workflowNotification ? { workflowNotification } : {}),
  };
}

/**
 * Snapshot-level facts → terminal determines the manifest payload of the branch.
 *
 * Only cast when the three final states (completed / failed / canceled) and the snapshot is present. `lost` (snapshot missing) and non-final states
 * Always returns `undefined` - the absence of a payload means that the GUI returns the current header line, rather than falsely reporting an empty shell. **usage/tokens launch
 * Time is unknown** (only in the memory state projection), so only durationMs is taken, and tokens are left to be checked by runId during the GUI rendering period.
 */
function buildWorkflowTerminalNotification(
  status: string,
  summary: string,
  snapshot: BackgroundTaskSnapshot | undefined,
): WorkflowNotificationMeta | undefined {
  const terminalStatus = workflowTerminalNotificationStatus(status);
  if (terminalStatus === undefined || snapshot === undefined) return undefined;

  const terminal = workflowSnapshotTerminal(status, snapshot);
  const meta: Extract<WorkflowNotificationMeta, { kind: "terminal" }> = {
    kind: "terminal",
    status: terminal?.runStatus ?? terminalStatus,
    ...(terminal?.stopReason === undefined ? {} : { stopReason: terminal.stopReason }),
    summary: summary.slice(0, WORKFLOW_NOTIFICATION_SUMMARY_MAX_CHARS),
  };

  // Product: any top-level return value of the script, uniformly serialized. Truncated honesty - `resultTruncated` Preview is partial when present,
  // The full amount is available via run id / GetWorkflowRun. Fork alignment of resultForm and serializeWorkflowArtifact:
  // string as is (prose), the rest JSON.stringify (json).
  const outputValue = snapshot && "output" in snapshot ? snapshot.output : undefined;
  const serialized = serializeWorkflowArtifact(outputValue);
  if (serialized !== undefined) {
    if (serialized.length > WORKFLOW_NOTIFICATION_RESULT_MAX_CHARS) {
      meta.result = serialized.slice(0, WORKFLOW_NOTIFICATION_RESULT_MAX_CHARS);
      meta.resultTruncated = true;
    } else {
      meta.result = serialized;
    }
    meta.resultForm = typeof outputValue === "string" ? "prose" : "json";
  }

  const error = snapshot && "error" in snapshot ? runtimeString(snapshot.error) : undefined;
  if (error !== undefined) meta.error = error.slice(0, WORKFLOW_NOTIFICATION_ERROR_MAX_CHARS);

  // The asymptotic product carries all three final states: a run that dies on the 12th ask still completes the work of the 11th ask.
  const reports = buildWorkflowReportsManifestSection(workflowSnapshotReports(snapshot));
  if (reports !== undefined) meta.reports = reports;

  // The chips load of the user interface product. This is the notification line chips
  // **The only** data source: hydration cold recovery reads it back as it is according to the shared zod. If a key is missing, it equals chips permanently.
  // disappear. All three final states are carried for the same reason as reports.
  const artifactsSection = buildWorkflowArtifactsManifestSection(
    workflowSnapshotArtifacts(snapshot),
  );
  if (artifactsSection !== undefined) {
    meta.artifacts = artifactsSection.artifacts;
    if (artifactsSection.artifactsTruncated) meta.artifactsTruncated = true;
  }

  const durationMs = workflowNotificationDurationMs(snapshot);
  if (durationMs !== undefined) meta.durationMs = durationMs;

  return meta;
}

/**
 * Tracker final state status → manifest's three final state literals (`failed` → errored, `cancelled` → stopped); non-final states (running / lost, etc.) return undefined (not carried
 * load). When the snapshot comes with `runStatus`, it shall prevail (see workflowSnapshotTerminal).
 */
function workflowTerminalNotificationStatus(
  status: string,
): "completed" | "errored" | "stopped" | undefined {
  switch (status) {
    case "completed":
      return "completed";
    case "failed":
      return "errored";
    case "cancelled":
      return "stopped";
    default:
      return undefined;
  }
}

/**
 * The wall clock duration in the notification (the "time" grid of the completion card).
 *
 * Two sources, whichever is greater:
 *   - This life: `completedAt - startedAt`, the segment that the process of settling it sees;
 *   - The active duration of the entire lineage: `activeDurationMs`, summed from the journal by the port (each life of resume +
 *     along each predecessor of `resumedFrom`), which is not read when absent.
 *
 * Only reporting the wall clock duration of this startup will miss the previous running time: revision and
 * resume each restarts the in-process clock once, and most of that time is cache replay. Taking the larger value instead of taking the lineage directly is to keep the
 * "Never report what this process has seen with your own eyes": The events of the old run are earlier than this accounting, and the journal reader is not present `activeDurationMs`
 * Absent, return to this life; and the lineage value is always larger than this life (it includes this life).
 *
 * Neither source reads the time field absent (written `—` on the card), and does not write 0.
 */
function workflowNotificationDurationMs(snapshot: BackgroundTaskSnapshot): number | undefined {
  const startedAt =
    "startedAt" in snapshot && snapshot.startedAt instanceof Date
      ? snapshot.startedAt.getTime()
      : undefined;
  const completedAt =
    "completedAt" in snapshot && snapshot.completedAt instanceof Date
      ? snapshot.completedAt.getTime()
      : undefined;
  const ownLifeMs =
    startedAt === undefined || completedAt === undefined
      ? undefined
      : nonNegativeFinite(completedAt - startedAt);
  const lineageMs =
    "activeDurationMs" in snapshot ? nonNegativeFinite(snapshot.activeDurationMs) : undefined;
  if (ownLifeMs === undefined) return lineageMs;
  return lineageMs === undefined ? ownLifeMs : Math.max(ownLifeMs, lineageMs);
}

/** Only non-negative finite numbers count as a duration; the rest (NaN / Infinity / negative numbers / non-numbers) are all read as "unspeakable". */
function nonNegativeFinite(value: unknown): number | undefined {
  return typeof value === "number" && Number.isFinite(value) && value >= 0 ? value : undefined;
}

/**
 * DWF progressive product on snapshot. `BackgroundTaskSnapshot` is a union type (bash/subagent/legacy
 * workflow/dwf), only the dwf one has `reports`, so press `in` to narrow rather than assert.
 * The form is still defensive checking: the input to this path comes from the port implementation, and the snapshot is a cross-package contract.
 */
/**
 * dwf script file on the snapshot (absolute path). The narrowing method is the same as {@link workflowSnapshotReports}
 * (`in` instead of assertion: `BackgroundTaskSnapshot` is a union of four, only the dwf one has this key), the shape then
 * Again typeof - snapshot is a cross-package contract, old ports/stubs may not have it at all.
 */
function workflowSnapshotScriptPath(
  snapshot: BackgroundTaskSnapshot | undefined,
): string | undefined {
  if (snapshot === undefined || !("scriptPath" in snapshot)) return undefined;
  return typeof snapshot.scriptPath === "string" && snapshot.scriptPath.length > 0
    ? snapshot.scriptPath
    : undefined;
}

function workflowSnapshotReports(
  snapshot: BackgroundTaskSnapshot | undefined,
): readonly unknown[] | undefined {
  if (snapshot === undefined || !("reports" in snapshot)) return undefined;
  return Array.isArray(snapshot.reports) ? snapshot.reports : undefined;
}

/**
 * The dwf **user surface artifact** on the snapshot (the output published by `artifact.*`, not the return value of `output`). narrow way
 * Same as {@link workflowSnapshotReports} (`in` instead of asserting: `BackgroundTaskSnapshot` is four
 * Union, only the dwf one has this key), the shape goes through defensive parsing again - the snapshot is a cross-package contract.
 */
function workflowSnapshotArtifacts(
  snapshot: BackgroundTaskSnapshot | undefined,
): ReturnType<typeof toPublishedArtifactSummaries> {
  if (snapshot === undefined || !("artifacts" in snapshot)) return undefined;
  return toPublishedArtifactSummaries(snapshot.artifacts);
}

function stringField(record: Record<string, unknown> | undefined, key: string): string | undefined {
  const value = record?.[key];
  return typeof value === "string" ? value : undefined;
}

function getBackgroundTaskWaiter(
  executionPort: ExecutionPort | undefined,
): BackgroundTaskWaiter | undefined {
  const candidate = executionPort as Partial<BackgroundTaskWaiter> | undefined;
  return typeof candidate?.waitForBackgroundTask === "function"
    ? (candidate as BackgroundTaskWaiter)
    : undefined;
}

function getWorkflowTaskWaiter(workflowPort: unknown): WorkflowTaskWaiter | undefined {
  const candidate = workflowPort as Partial<WorkflowTaskWaiter> | undefined;
  return typeof candidate?.waitForTask === "function"
    ? (candidate as WorkflowTaskWaiter)
    : undefined;
}

/**
 * Display categories of background tasks (panel groups and icons). `taskKind` is just decoration: lifecycle semantics have been changed by
 * Per-tool lifecycleProvider dispatch, so classification changes here will not affect observe/wait/cancel.
 *
 * legacy `Workflow` (script workflow) is deliberately still "bash": it cannot be canceled and there is no details page on the panel.
 * and workflow run are two different things, sharing a category will cause the panel to mix the two together.
 */
function backgroundTaskKind(toolName: string): "bash" | "subagent" | "workflow" {
  if (isSubagentDispatchToolName(toolName)) return "subagent";
  // The two entries of dwf (CreateWorkflow / ResumeWorkflowRun) belong to the same "workflow": the same run
  // The life cycle continues, and panel groups and icons should not be changed due to different entrances.
  return isDynamicWorkflowRunDispatchToolName(toolName) ? "workflow" : "bash";
}
