// Concurrency racing between PermissionRequest hook chains and interactive brokers.
//
// Old path serial await hook after emitPermissionRequested
// chain, the broker's response deferred will not be registered until the hook returns. Synchronous hook (redirect permission request to external UI and
// While a bridge program (blocking waiting for external clicks) is suspended, the confirmation window is visible to the user, but all clicks are blocked.
// resolveInteraction is discarded according to "Missed is idempotent success" - the confirmation window dies permanently, and turn hangs permanently.
// Modification: Two responders start concurrently, the decision that comes first takes effect, and the loser aborts immediately without waiting.
import type { PermissionBrokerResult } from "@zcode/contracts";
import { linkAbortSignal } from "./timeout.js";

interface PermissionResponderRaceInput {
  /**
   * hook chain responder. resolve `undefined` means no decision (retirement, leaving only the broker waiting unilaterally);
   * Errors are also handled as race exit and callback {@link PermissionResponderRaceInput.onHookFailure}——
   * Infrastructure failures on the secondary responder should not make the denial decision for the user.
   */
  runHooks: (signal: AbortSignal) => Promise<PermissionBrokerResult | undefined>;
  /**
   * broker responder. The response channel (v4 interaction deferred / TUI approval queue) must be in this function
   * Synchronous establishment within the call - this is the prerequisite for the confirmation window to be "visible and answered", guaranteed by the existing broker contract.
   * Rejection (timeout, cancellation, fail-closed) is thrown as it is when the hook does not win, and the error form is consistent with the old serial path.
   */
  requestBroker: (
    signal: AbortSignal,
    claimResponse: () => boolean,
  ) => Promise<PermissionBrokerResult>;
  /** The outer turn cancels the signal: abort both sides, and then the broker rejects the previous one and throws it up. */
  signal?: AbortSignal;
  /** Called back when the hook chain throws an error and the race has not yet closed (the caller records a warn log). */
  onHookFailure?: (error: unknown) => void;
}

interface PermissionResponderRaceOutcome {
  result: PermissionBrokerResult;
  source: "hook" | "broker";
}

export async function racePermissionResponders(
  input: PermissionResponderRaceInput,
): Promise<PermissionResponderRaceOutcome> {
  const hookController = new AbortController();
  const brokerController = new AbortController();
  const unlinkHook = linkAbortSignal(input.signal, hookController);
  const unlinkBroker = linkAbortSignal(input.signal, brokerController);

  let settled = false;
  let brokerClaimed = false;
  try {
    return await new Promise<PermissionResponderRaceOutcome>((resolve, reject) => {
      const settle = (action: () => void, abortLoser: AbortController) => {
        if (settled) return;
        settled = true;
        action();
        // Cash the result first and then abort the loser: the loser's ending (child process termination, reverse RPC cancellation) must not
        // In turn, it blocks the winner - the loser is the one who is dying.
        abortLoser.abort();
      };

      // The broker starts first: synchronously registers the response deferred in requestPermission to ensure that the confirmation window is visible.
      // Users will find their destination when they click, leaving no exclusive window period for hooks.
      input
        .requestBroker(brokerController.signal, () => {
          if (settled || brokerController.signal.aborted) return false;
          brokerClaimed = true;
          hookController.abort();
          return true;
        })
        .then(
          (result) => settle(() => resolve({ result, source: "broker" }), hookController),
          (error) => {
            // After the hook wins, we actively abort the rejection generated by the broker, which is our own cancellation and swallowing;
            // Rejection when the race is not closed (timeout/outer layer cancellation/fail-closed) is a real error and will be thrown as it is.
            settle(() => reject(error), hookController);
          },
        );

      input.runHooks(hookController.signal).then(
        (decision) => {
          // No decision = Retirement: The racing status is not transferred and the broker continues to wait unilaterally.
          if (decision === undefined || brokerClaimed) return;
          settle(() => resolve({ result: decision, source: "hook" }), brokerController);
        },
        (error) => {
          if (settled) return;
          input.onHookFailure?.(error);
        },
      );
    });
  } finally {
    unlinkHook();
    unlinkBroker();
  }
}
