import type { ApplicationIconRequest } from "@zcode/shared";

/**
 * producer's `appKey` → platform icon locator.
 *
 * `appKey` is generated by zcode-cua's `deriveApplicationKey`, and its form is `<scheme>:<value>`:
 * `darwin:<bundleId>` (lowercase), `windows-aumid:<aumid>`, `windows-exe:<canonical path>`,
 * `linux-exe:<path>`. The session protocol only carries this string, and the icon bytes are fetched by the platform service according to the locator.
 *
 * Linux does not have a corresponding `ApplicationIconLocator` kind, and there is no resolver on the desktop side, so null is returned.
 * The caller falls back to its own generic icon.
 */
const APP_KEY_LOCATOR_KINDS = {
  darwin: "darwin-bundle-id",
  "windows-aumid": "windows-aumid",
  "windows-exe": "windows-executable-path",
} as const satisfies Record<string, ApplicationIconRequest["locators"][number]["kind"]>;

export function cuaAppKeyToIconRequest(
  appKey: string | undefined | null,
): ApplicationIconRequest | null {
  if (!appKey) return null;
  // Only cut the first colon: the Windows exe path itself has a drive letter colon, and the global split will cut `c:\...` into `c`.
  const separator = appKey.indexOf(":");
  if (separator <= 0) return null;
  const scheme = appKey.slice(0, separator);
  const value = appKey.slice(separator + 1).trim();
  if (!value) return null;
  const kind = (APP_KEY_LOCATOR_KINDS as Record<string, string | undefined>)[scheme];
  if (!kind) return null;
  return { locators: [{ kind, value } as ApplicationIconRequest["locators"][number]] };
}
