// ConversationRow: The row type is self-contained.
// Three structural rules: row is self-contained (rendering any row does not require looking at other rows);
// For structural changes, the entire row is replaced (row.upserted), and for text growth, append (row.delta) is used; turn is the label on the row, not the container.
import { z } from "zod";
import { executionOutputPreviewSchema } from "../execution-output-preview.js";
import { timestampSchema } from "./core.js";
import { backgroundResultOriginMetaSchema, workflowLaunchMetaSchema } from "./workflow-row-meta.js";

// RowBase. rowId: a deterministic pure function that is monotonous, never reused, and event log within the session.
const rowBaseFields = {
  rowId: z.number(),
  turnId: z.string(),
  // canonical identity: Each line of the new CLI must be passed; optional is only used for compatibility with legacy frames.
  // entityId locates the persistent entity, productTurnId is the product turn and must not be reguessed by the UI.
  entityId: z.string().min(1).optional(),
  productTurnId: z.string().min(1).optional(),
  visibility: z.literal("visible").optional(),
  createdAt: timestampSchema,
  createdAtSeq: z.number(),
  // The default is all false; only keys that are true are delivered. canRewind is not in the payload (UI entry for rewind = editUserQuery).
  actions: z
    .object({
      canFork: z.literal(true).optional(),
      canEdit: z.literal(true).optional(),
      canRetry: z.literal(true).optional(),
      canRewindFiles: z.literal(true).optional(),
      editDisposition: z.enum(["rewind", "fork"]).optional(),
    })
    .optional(),
} as const;

export const rowActionsSchema = rowBaseFields.actions;
export type RowActions = NonNullable<z.infer<typeof rowActionsSchema>>;

// The row-level metadata of the workflow wheel is split into workflow-row-meta.ts (max-lines); the name is exported here as is.
export {
  backgroundResultOriginMetaSchema,
  workflowLaunchMetaSchema,
  workflowNotificationMetaSchema,
  workflowSettingsAmendMetaSchema,
  type BackgroundResultOriginMeta,
  type WorkflowLaunchMeta,
  type WorkflowNotificationMeta,
  type WorkflowSettingsAmendMeta,
} from "./workflow-row-meta.js";

export const turnWorkSegmentSchema = z.object({
  segmentId: z.string().min(1),
  triggerEntityId: z.string().min(1).optional(),
  startedAt: timestampSchema,
  endedAt: timestampSchema.optional(),
  activeMs: z.number().nonnegative().optional(),
});
export type TurnWorkSegment = z.infer<typeof turnWorkSegmentSchema>;

// turnHeader: product turn boundary + authoritative hours + document summary for each round.
// Internal fold boundaries generated by the guide are expressed by workSegments; row ownership is still determined by the CLI, with zero client-side ownership logic.
export const turnHeaderRowSchema = z.object({
  ...rowBaseFields,
  kind: z.literal("turnHeader"),
  // workflowLaunch: The controlOnly wheel launched directly by the hub.
  // Documented Skew: Closed Enum Bonus → Old Desktop + New CLI This line is thrown when parse fails (same as below
  // backgroundSource: "workflow" (added in the same file), CLI and desktop are accepted in the same batch release.
  origin: z.enum([
    "userInput",
    "backgroundResult",
    "goalContinuation",
    "editRerun",
    "workflowLaunch",
  ]),
  // Execution semantics are arbitrated by the CLI projection; the UI may not infer based on input text or duration.
  // optional is only used for compatibility with old snapshots, and new turnHeader must be written explicitly.
  executionKind: z.enum(["agent", "controlOnly"]).optional(),
  // The command attribution of the current query and the number of historical rounds; optional is compatible with old transcript/snapshot.
  sourceCommandId: z.string().optional(),
  historyRoundCount: z.number().int().nonnegative().optional(),
  state: z.enum(["running", "completedSuccess", "completedInterrupted", "failed"]),
  startedAt: timestampSchema,
  endedAt: timestampSchema.optional(),
  // Authoritative hours: Exclude permission waits/user input waits/verifier waits.
  activeMs: z.number().optional(),
  // Guide does not cut product turn, but each accepted guide opens an independent visual work segment.
  // Normal turn defaults to maintain compatibility with old snapshots; once the guide appears, the CLI is responsible for fully projecting the first segment and subsequent segments.
  workSegments: z.array(turnWorkSegmentSchema).optional(),
  originMeta: backgroundResultOriginMetaSchema.optional(),
  // origin === "workflowLaunch"'s on-wheel presence (live projection source); juxtaposed with originMeta, without reusing its shape.
  workflowLaunch: workflowLaunchMetaSchema.optional(),
  fileChanges: z
    .object({
      additions: z.number(),
      deletions: z.number(),
      files: z.number(),
      state: z.enum(["active", "reverted"]).optional(),
    })
    .optional(),
});
export type TurnHeaderRow = z.infer<typeof turnHeaderRowSchema>;

// userInput. originMeta eliminates text sniffing.
export const userInputRowSchema = z.object({
  ...rowBaseFields,
  kind: z.literal("userInput"),
  text: z.string(),
  // text Starting from this subscript is the engine additional text (dwf ask endnote /
  // nudge), the GUI folds it into the default collapsed disclosure; 0 = the entire item; absent = none (old transcription, non-workflow sessions).
  epilogueStart: z.number().int().nonnegative().optional(),
  // workflowLaunch: The hub directly launches the user-visible row of the wheel.
  // The message text still enters text (the downgraded presentation of the old client/TUI is the standard English sentence); the new client uses the following
  // workflowLaunch metadata draws run cards instead of bubbles at the end of the wheel. The skew of closed set additions is the same as the turnHeader.origin annotation.
  origin: z.enum([
    "realUser",
    "backgroundResult",
    "goalContinuation",
    "mailbox",
    "synthetic",
    "workflowLaunch",
  ]),
  originMeta: z
    .object({
      // The same set of values ​​as backgroundResultOriginMetaSchema (including "workflow" of workflow run).
      backgroundSource: z.enum(["bash", "subagent", "workflow"]).optional(),
      workId: z.string().optional(),
      senderSessionId: z.string().optional(),
      senderLabel: z.string().optional(),
    })
    .optional(),
  // Present on the line origin === "workflowLaunch"; juxtaposed with originMeta, same as turnHeader.
  workflowLaunch: workflowLaunchMetaSchema.optional(),
  // Injected via turn-steer (guideModeTurnSteer).
  guided: z.literal(true).optional(),
  // realUser/guided is required; the system source is default. overlay closing anchor point.
  sourceCommandId: z.string().optional(),
  // edit/retry will generate a new sourceCommandId; this field is fixed to the canonical input root.
  // Used for one-time recovery of budget and other lineage judgments across reruns. Old transcript can be defaulted.
  rootSourceCommandId: z.string().optional(),
  // Submitter identity is written by CLI admission; old transcript can be defaulted.
  clientId: z.string().optional(),
  attachments: z
    .array(
      z.object({
        ref: z.string(),
        fileName: z.string(),
        mime: z.string(),
        bytes: z.number(),
        previewRef: z.string().optional(),
      }),
    )
    .optional(),
});
export type UserInputRow = z.infer<typeof userInputRowSchema>;

// assistantText / reasoning.
// Invariant: Only rows with state="streaming" can be appended; a normal new response must have a new rowId. The only exception is
// ProductProjection output-token Continue confirmed by length/zero-tool fact, will reopen the same turn
// And the visually adjacent assistantText row; the client still only observes the standard row.upserted + row.delta.
export const assistantTextRowSchema = z.object({
  ...rowBaseFields,
  kind: z.literal("assistantText"),
  // The body of the same model response shares this ID with the tool; optional is compatible with older snapshots.
  assistantResponseId: z.string().min(1).optional(),
  text: z.string(),
  state: z.enum(["streaming", "complete", "interrupted", "failed"]),
  model: z.string().optional(),
  feedback: z.enum(["like", "dislike"]).optional(),
});
export type AssistantTextRow = z.infer<typeof assistantTextRowSchema>;

export const reasoningRowSchema = z.object({
  ...rowBaseFields,
  kind: z.literal("reasoning"),
  // Thoughts, text and tools of the same model response share this ID; optional is compatible with old snapshots.
  assistantResponseId: z.string().min(1).optional(),
  text: z.string(),
  state: z.enum(["streaming", "complete", "interrupted"]),
  durationMs: z.number().optional(),
});
export type ReasoningRow = z.infer<typeof reasoningRowSchema>;

// toolCall display layer schema has been split into ./toolDisplay.ts (rows.ts is subject to max-lines constraints).
import { toolCallDisplaySchema, toolOutputSchema, toolProgressSchema } from "./toolDisplay.js";

export const cuaAppIdentitySchema = z
  .object({
    pid: z.number().int().positive(),
    name: z.string().trim().min(1).max(256),
    bundleId: z.string().trim().min(1).max(512).optional(),
  })
  .strict();
export type CuaAppIdentity = z.infer<typeof cuaAppIdentitySchema>;

export const toolCallRowSchema = z.object({
  ...rowBaseFields,
  kind: z.literal("toolCall"),
  // The body of the same model response shares this ID with the tool; optional is compatible with older snapshots.
  assistantResponseId: z.string().min(1).optional(),
  toolCallId: z.string(),
  toolName: z.string(),
  status: z.enum(["inputStreaming", "pendingApproval", "running", "success", "error", "cancelled"]),
  inputText: z.string(),
  input: z.unknown().optional(),
  cuaApp: cuaAppIdentitySchema.optional(),
  output: toolOutputSchema.optional(),
  // If display parsing fails, only the payload of this card will be discarded, and the entire row will not be rejected (for the reason, see toolOutputSchema of toolDisplay.ts
  // Note: Decoration payloads must not determine the life or death of a row/frame/subscription).
  display: toolCallDisplaySchema.optional().catch(undefined),
  // Required when status=error.
  error: z.object({ code: z.string(), message: z.string() }).optional(),
  // Only replayable files appear during operation and are cleared in the final state.
  progress: toolProgressSchema.optional(),
  // continuous/replayable shared bounded Bash content, cleared on final state or background handover.
  outputPreview: executionOutputPreviewSchema.optional(),
  // When status=pendingApproval points to the pendingInteractions item.
  approvalInteractionId: z.string().optional(),
  backgrounded: z.literal(true).optional(),
  workId: z.string().optional(),
  startedAt: timestampSchema.optional(),
  endedAt: timestampSchema.optional(),
});
export type ToolCallRow = z.infer<typeof toolCallRowSchema>;

// The shared result object is part of the formal projection of the session; the ref in the local projection is a read reference authorized by the Host.
// Publicly shared projections must be replaced with zcode-artifact://share/:id, and transparent transmission of local paths is prohibited.
export const conversationArtifactTypeSchema = z.enum([
  "pdf",
  "pptx",
  "docx",
  "xlsx",
  "image",
  "html",
  "md",
  "text",
]);
export type ConversationArtifactType = z.infer<typeof conversationArtifactTypeSchema>;

export const artifactRowSchema = z.object({
  ...rowBaseFields,
  kind: z.literal("artifact"),
  artifactVersionId: z.string().trim().min(1),
  logicalArtifactKey: z.string().trim().min(1),
  displayName: z.string().trim().min(1),
  artifactType: conversationArtifactTypeSchema,
  mimeType: z.string().trim().min(1),
  sizeBytes: z.number().int().nonnegative(),
  sha256: z.string().regex(/^[0-9a-f]{64}$/u),
  ref: z.string().trim().min(1),
  state: z.literal("current"),
});
export type ArtifactRow = z.infer<typeof artifactRowSchema>;

// subagent. Prerequisite: subagent mirroring events must be entered into the event log.
export const subagentRowSchema = z.object({
  ...rowBaseFields,
  kind: z.literal("subagent"),
  // Triggers the Agent/Task tool call for this subagent; concurrent spawn order cannot be used as a basis for correlation.
  parentToolCallId: z.string().optional(),
  subagentType: z.string(),
  status: z.enum(["running", "success", "failed", "cancelled"]),
  summaryText: z.string(),
  // Exists → UI drill-down subscription conversation/<childSessionId> (without inline child rows).
  childSessionId: z.string().optional(),
  backgrounded: z.literal(true).optional(),
  workId: z.string().optional(),
  startedAt: timestampSchema.optional(),
  endedAt: timestampSchema.optional(),
});
export type SubagentRow = z.infer<typeof subagentRowSchema>;

// Hook runtime descriptor is only compatible with CLI event/projection input. Dialog wire row use below
// client-safe summary, does not carry commands, absolute paths, stdin/stdout/stderr/tool input or environment variables.
export const hookExecutionDescriptorSchema = z
  .object({
    clientVisible: z.literal(true),
    sourceKind: z.enum(["user", "plugin", "project", "internal"]),
    sourcePath: z.string().optional(),
    pluginId: z.string().optional(),
    pluginName: z.string().optional(),
    statusMessage: z.string().optional(),
    executionType: z.enum(["process", "command"]),
    executionMode: z.enum(["foreground", "background"]),
    commandDisplay: z.string(),
    timeoutMs: z.number().int().positive(),
  })
  .strict();
export type HookExecutionDescriptor = z.infer<typeof hookExecutionDescriptorSchema>;

export const hookExecutionProjectionSchema = z
  .object({
    hookRunId: z.string().min(1),
    hookIndex: z.number().int().nonnegative(),
    // True if HookRunStarted has been observed for the same runId; false if admission-only blocked.
    didExecute: z.boolean(),
    state: z.enum(["running", "completed", "failed"]),
    outcome: z.enum(["success", "blocked", "failed", "cancelled", "timed_out"]).optional(),
    blockReason: z.string().trim().min(1).optional(),
    startedAt: timestampSchema,
    endedAt: timestampSchema.optional(),
    durationMs: z.number().nonnegative().optional(),
    displayName: z.string().trim().min(1),
    sourceKind: z.enum(["user", "plugin", "project"]),
    pluginName: z.string().optional(),
    toolName: z.string().optional(),
  })
  .strict();
export type HookExecutionProjection = z.infer<typeof hookExecutionProjectionSchema>;

export const hookInvocationRowSchema = z.object({
  ...rowBaseFields,
  kind: z.literal("hookInvocation"),
  hookInvocationId: z.string().min(1),
  hookEventName: z.enum([
    "SessionStart",
    "UserPromptSubmit",
    "PreToolUse",
    "PermissionRequest",
    "PostToolUse",
    "PostToolUseFailure",
    "Stop",
  ]),
  hookCount: z.number().int().positive(),
  state: z.enum(["running", "completed", "failed"]),
  startedAt: timestampSchema,
  endedAt: timestampSchema.optional(),
  durationMs: z.number().nonnegative().optional(),
  lane: z.enum(["assistantWork", "toolBefore", "toolAfter"]),
  anchorToolCallId: z.string().optional(),
  executions: z.array(hookExecutionProjectionSchema),
});
export type HookInvocationRow = z.infer<typeof hookInvocationRowSchema>;

// timelineMarker.
// compact.status=cancelled means that auto compact is stopped; the final failure status is failed.
export const timelineMarkerPayloadSchema = z.union([
  z.object({
    type: z.literal("compact"),
    origin: z.enum(["manual", "auto"]),
    status: z.enum(["running", "success", "failed", "noop", "cancelled"]),
    tokensBefore: z.number().optional(),
    tokensAfter: z.number().optional(),
    summaryRef: z.string().optional(),
  }),
  // Appears in the child session header (forkTimelineIsBoundary).
  z.object({
    type: z.literal("forkNotice"),
    parentSessionId: z.string(),
    parentRowId: z.number(),
  }),
  // Appears in parent (optional display).
  z.object({
    type: z.literal("forkCreated"),
    childSessionId: z.string(),
    atRowId: z.number(),
  }),
  z.object({
    type: z.literal("modelChange"),
    fromProvider: z.string(),
    fromModel: z.string(),
    toProvider: z.string(),
    toModel: z.string(),
    toThought: z.string(),
  }),
  z.object({
    type: z.literal("modelChange"),
    // Explicit ∅→X model boundary has no source; never ensures that only one of the two source fields cannot appear.
    // Avoid the renderer receiving half a provider/model tuple.
    fromProvider: z.never().optional(),
    fromModel: z.never().optional(),
    toProvider: z.string(),
    toModel: z.string(),
    toThought: z.string(),
  }),
  z.object({
    type: z.literal("goalSet"),
    objective: z.string(),
    previousObjective: z.string().optional(),
  }),
  z.object({
    type: z.literal("goalVerify"),
    iteration: z.number(),
    outcome: z.enum(["running", "pass", "notSatisfied", "failed"]),
    detail: z.string().optional(),
  }),
  z.object({
    type: z.literal("retryNotice"),
    attempt: z.number(),
    reasonCode: z.string(),
  }),
  // The receipt of the workspace domain action on the timeline.
  z.object({
    type: z.literal("checkpointRestored"),
    checkpointId: z.string(),
  }),
]);
export type TimelineMarkerPayload = z.infer<typeof timelineMarkerPayloadSchema>;

/**
 * marker lane:
 * The placement semantics are determined by CLI projection. The UI is only assembled by lane and cannot be inferred by marker type.
 * - assistantWork: assistant work activity (compact), enter the "Worked" folding group;
 * - turnTailBoundary: turnTailBoundary (goalVerify/forkNotice), leaving the end of the turn unfolded;
 * - lightBoundary: wheel top light boundary (modelChange), rendered before user input.
 * optional = compatible with old snapshots (by default, the UI falls back to mapping according to marker type).
 */
export const timelineMarkerLaneSchema = z.enum([
  "assistantWork",
  "turnTailBoundary",
  "lightBoundary",
]);
export type TimelineMarkerLane = z.infer<typeof timelineMarkerLaneSchema>;

export const timelineMarkerRowSchema = z.object({
  ...rowBaseFields,
  kind: z.literal("timelineMarker"),
  // Required for user-triggered markers.
  sourceCommandId: z.string().optional(),
  lane: timelineMarkerLaneSchema.optional(),
  marker: timelineMarkerPayloadSchema,
});
export type TimelineMarkerRow = z.infer<typeof timelineMarkerRowSchema>;

export const conversationRowSchema = z.discriminatedUnion("kind", [
  turnHeaderRowSchema,
  userInputRowSchema,
  assistantTextRowSchema,
  reasoningRowSchema,
  toolCallRowSchema,
  artifactRowSchema,
  subagentRowSchema,
  hookInvocationRowSchema,
  timelineMarkerRowSchema,
]);
export type ConversationRow = z.infer<typeof conversationRowSchema>;
export type ConversationRowKind = ConversationRow["kind"];
