// Birth fact reading: Generates actor entries as per protocol capacity cap.
// Pure function, does not read the clock or perform I/O.
//
// Names and stage names are generated by scripts and may exceed the protocol length limit. The rendering end will strictly verify each frame, and long values may cause
// Both incremental and recovery snapshots are rejected. So the producer is clipped to the schema cap and the full value remains in the journal.

import { WORKFLOW_RUNS_LIMITS, type WorkflowRunActor } from "./workflow-runs.js";

/**
 * Mints one actor entry. The two call sites must be **word-for-word identical in shape**:
 * `actor-created`, and the `node-dispatched` that carries a birth fact (the activation in
 * workflow-runs-eviction.ts) — the same subagent growing two different entry shapes depending
 * on its arrival path is two records that will not match on a cold replay.
 *
 * `status` is a placeholder value: the immediately following `withDerivedWorkflowActorStatuses`
 * recomputes it from the nodes and the run's terminal state.
 */
export function workflowActorEntry(
  ref: { siteId: string; ordinal: number },
  name: unknown,
  phaseName: string | undefined,
  sessionId: string | undefined,
): WorkflowRunActor {
  const bounded = boundedActorName(nonEmptyString(name));
  return {
    siteId: ref.siteId,
    ordinal: ref.ordinal,
    ...(bounded === undefined ? {} : { name: bounded }),
    ...(sessionId ? { sessionId } : {}),
    ...(phaseName === undefined ? {} : { phaseName }),
    status: "waiting",
  };
}

/** Wire bound for a subagent display name (see the subscription rejection described in the file header). */
export function boundedActorName(name: string | undefined): string | undefined {
  return name === undefined ? undefined : name.slice(0, WORKFLOW_RUNS_LIMITS.maxActorNameLength);
}

/**
 * Wire bound for an instance's birth phase name. Same family and same reasoning as
 * {@link boundedActorName}, but it **truncates directly, without an ellipsis** — this field is
 * not human-readable text but a correlation key, and the UI's `phaseNameMatches` correlates the
 * truncated name back to the display phase precisely by prefix.
 */
export function boundedPhaseName(name: string | undefined): string | undefined {
  return name === undefined ? undefined : name.slice(0, WORKFLOW_RUNS_LIMITS.maxPhaseNameLength);
}

/** An empty string is treated as absent: on the protocol wire there are only "key present" and "key absent". */
export function nonEmptyString(value: unknown): string | undefined {
  return typeof value === "string" && value.length > 0 ? value : undefined;
}
