// Virtual scrolling core: v4 timeline bottom-anchored state machine (pure function, no DOM/React dependencies).
//
// Semantics (scrollAnchor):
// - The user is at the bottom → following=true, new content (new line/streaming delta/altitude change) is automatically posted to the bottom;
// - The user scrolls up and away from the bottom → following=false, the streaming increment cannot be pulled back to the reading position, and the "Back to Bottom" button appears;
// - The user manually scrolls back to the bottom (or clicks the button) → resume following.
//
// The following expresses user scrolling rights, not an instantaneous geometry snapshot: only real user scrolling input can change it;
// The scroll events generated by programmatic bottoming, terminal folding, and virtualizer height compensation only update the geometry account.
//

/**
 * Tolerance for the at-bottom verdict: a distance below it counts as "at the bottom". The value
 * covers subpixel scrolling and the last row's padding.
 */
const BOTTOM_ANCHOR_EPSILON_PX = 48;

interface TimelineScrollMetrics {
  /** The scroll container's scrollTop. */
  scrollTop: number;
  /** The scroll container's visible height (clientHeight). */
  viewportHeight: number;
  /** The total content height (scrollHeight). */
  contentHeight: number;
}

/**
 * The remaining scrollable distance to the bottom (0 when the content is shorter than one screen).
 */
export function distanceToBottom(metrics: TimelineScrollMetrics): number {
  return Math.max(0, metrics.contentHeight - metrics.viewportHeight - metrics.scrollTop);
}

export function isAtBottom(
  metrics: TimelineScrollMetrics,
  epsilonPx: number = BOTTOM_ANCHOR_EPSILON_PX,
): boolean {
  return distanceToBottom(metrics) <= epsilonPx;
}

/**
 * The follow state after a scroll event. Rule: landing at the bottom ⇔ following. It covers all
 * three sources without having to distinguish them: the user scrolling up (away from the bottom →
 * released), the user scrolling back down (against the bottom → restored), and a programmatic
 * scroll to the bottom (landing at the bottom → kept).
 */
function nextFollowingAfterScroll(
  metrics: TimelineScrollMetrics,
  epsilonPx: number = BOTTOM_ANCHOR_EPSILON_PX,
): boolean {
  return isAtBottom(metrics, epsilonPx);
}

type TimelineScrollEventSource = "user" | "programmatic" | "layout";

/**
 * The scroll-authority verdict after a scroll event. Layout / programmatic scrolls must not change
 * the user's intent; only user input decides whether to follow, based on the final landing point.
 */
export function resolveFollowingAfterScroll(input: {
  following: boolean;
  metrics: TimelineScrollMetrics;
  source: TimelineScrollEventSource;
  epsilonPx?: number;
}): boolean {
  if (input.source !== "user") return input.following;
  return nextFollowingAfterScroll(input.metrics, input.epsilonPx);
}

/**
 * The action after a content change (a new row appended / a streaming delta growing taller / a
 * dynamic measurement correction): while following → stick to the bottom; once released → keep the
 * reading position (never pull back).
 */
export function anchorActionAfterContentChange(
  following: boolean,
  contentWidthChanging: boolean = false,
): "stickToBottom" | "hold" {
  return following && !contentWidthChanging ? "stickToBottom" : "hold";
}

/**
 * The scroll compensation verdict after the virtualizer measures dynamically. A width resize makes
 * many messages get measured in batches across adjacent frames; compensating scrollTop item by item
 * then produces visible jitter.
 */
export function shouldAdjustVirtualizerForItemSizeChange(input: {
  following: boolean;
  suppressAdjustment: boolean;
  contentWidthChanging: boolean;
  itemEnd: number;
  scrollTop: number;
}): boolean {
  if (input.suppressAdjustment || input.following || input.contentWidthChanging) {
    return false;
  }
  return input.itemEnd <= input.scrollTop;
}

/**
 * Tolerance for the unobserved-scroll verdict: a scrollTop below this value that goes backwards is
 * subpixel jitter, not a user scroll-up.
 */
const UNOBSERVED_SCROLL_EPSILON_PX = 2;

export type TimelineUserScrollIntent = "none" | "awayFromBottom" | "towardBottom" | "unknown";

/**
 * A wheel's deltaY runs in the same direction as scrollTop: a negative value reads earlier content,
 * a positive value moves towards the bottom.
 */
export function timelineWheelScrollIntent(deltaY: number): TimelineUserScrollIntent {
  if (deltaY < 0) return "awayFromBottom";
  if (deltaY > 0) return "towardBottom";
  return "none";
}

/**
 * A touch finger's displacement runs opposite to scrollTop: a downward finger means reading earlier
 * content.
 */
export function timelineTouchScrollIntent(
  previousClientY: number,
  nextClientY: number,
): TimelineUserScrollIntent {
  if (nextClientY > previousClientY) return "awayFromBottom";
  if (nextClientY < previousClientY) return "towardBottom";
  return "none";
}

/** Keyboard scroll intent; caret keys inside an input control are not timeline scrolling. */
export function timelineKeyboardScrollIntent(input: {
  key: string;
  shiftKey: boolean;
  editableTarget: boolean;
}): TimelineUserScrollIntent {
  if (input.editableTarget) return "none";
  if (input.key === "ArrowUp" || input.key === "PageUp" || input.key === "Home") {
    return "awayFromBottom";
  }
  if (input.key === "ArrowDown" || input.key === "PageDown" || input.key === "End") {
    return "towardBottom";
  }
  if (input.key === " ") {
    return input.shiftKey ? "awayFromBottom" : "towardBottom";
  }
  return "none";
}

/**
 * Reconcile the user's scroll intent before a content-change commit sticks to the bottom.
 *
 * The follow state is driven by scroll events, but a scroll event is only dispatched on the render
 * frame after the scroll happens: after the user scrolls up (wheel) or a test assigns scrollTop
 * programmatically, and before the event is dispatched, if it happens to land inside a React commit
 * where totalSize/rowCount changes (a streaming delta, a ResizeObserver measurement correction, the
 * window recomputation caused by a composer size change), the stick-to-bottom effect takes the
 * **stale following=true** and drags scrollTop back to the bottom, and the bounce landing point
 * makes the subsequent scroll event judge following back to true — the user's / the test's
 * scroll-up is swallowed wholesale ("a resize/measurement commit stole the scroll authority").
 *
 * Reconciliation rules (executed before the stick-to-bottom action, with the live metrics as of the
 * commit):
 * 1. An explicit upward scroll → release following immediately; a terminal/layout commit in the
 *    same frame must yield as well;
 * 2. No user input → keep following as it is; a scrollTop regression caused by the
 *    virtualizer/collapsing does not count as scrolling up;
 * 3. Direction unknown, or downward user input → restore following if the landing point is at the
 *    bottom, release on a clear regression, otherwise keep.
 */
export function reconcileFollowingForContentAnchor(input: {
  /** The current follow state (the existing value driven by scroll events). */
  following: boolean;
  /** The live scroll metrics at commit time (before the stick-to-bottom action). */
  metrics: TimelineScrollMetrics;
  /**
   * The component's most recently "reconciled" scrollTop (the value read by a scroll event, or read
   * back after a programmatic write).
   */
  lastObservedScrollTop: number;
  /**
   * The user's scroll intent captured before the current content commit; when omitted,
   * reconciliation falls back to the legacy unknown source.
   */
  userScrollIntent?: TimelineUserScrollIntent;
  bottomEpsilonPx?: number;
  scrollEpsilonPx?: number;
}): boolean {
  const userScrollIntent = input.userScrollIntent ?? "unknown";
  if (userScrollIntent === "awayFromBottom") return false;
  if (userScrollIntent === "none") return input.following;
  if (isAtBottom(input.metrics, input.bottomEpsilonPx ?? BOTTOM_ANCHOR_EPSILON_PX)) {
    return true;
  }
  const unobservedUpscroll =
    input.metrics.scrollTop <
    input.lastObservedScrollTop - (input.scrollEpsilonPx ?? UNOBSERVED_SCROLL_EPSILON_PX);
  if (unobservedUpscroll) {
    return false;
  }
  return input.following;
}

/**
 * Visibility of the "back to bottom" button: shown only when following is released and there really
 * is content.
 */
export function shouldShowBackToBottom(following: boolean, rowCount: number): boolean {
  return !following && rowCount > 0;
}

/**
 * Session switch / first bind: reset to following (opening a session locates the newest message).
 */
export function initialFollowing(): boolean {
  return true;
}

// ── loadOlder: prepend scroll anchoring (a classic pitfall of virtual scroll forward insertion)──
//
// Semantics: When inserting a history line forward to the top of the window, the position of the line the user is reading (the anchor point) must not jump in the viewport.
// Forward insertion under the virtual list only changes the total height (the existing turn caches the measurement value according to turnId, and does not re-hang or re-measure),
// Therefore, anchor recovery = scrollTop translates "the section where the content is pushed forward":
//   scrollTop' = scrollTop + (nextTotalSize - prevTotalSize)
// Prerequisite: The existing render unit key is stable (getItemKey=turnId) and there are no other measurement corrections in the same frame——
// New lines in prepend commit only have estimated heights, and subsequent ResizeObserver corrections use virtualizer
// The regular shift logic no longer goes through this function.

export interface PrependVirtualAnchor {
  key: string;
  /** The offset of the anchor's measurement start relative to the top of the viewport. */
  offsetTop: number;
  start: number;
}

/**
 * The scrollTop correction to apply to the same stable key after a prepend.
 *
 * Between triggering loadOlder and the rows commit, restoring the layout or the virtualizer may
 * rewrite scrollTop first; adding only the delta of measurement.start double-counts that
 * intermediate displacement. Computing the absolute target from the viewport offset captured at the
 * triggering instant, and then subtracting the live scrollTop, is what reliably restores the
 * original reading position.
 */
export function prependVirtualAnchorAdjustment(
  previous: PrependVirtualAnchor,
  next: PrependVirtualAnchor,
  currentScrollTop: number,
): number | null {
  if (previous.key !== next.key) return null;
  if (
    !Number.isFinite(previous.offsetTop) ||
    !Number.isFinite(next.start) ||
    !Number.isFinite(currentScrollTop)
  ) {
    return null;
  }
  return next.start - previous.offsetTop - currentScrollTop;
}

interface PrependAnchorInput {
  /** The window's first rowId of the previous commit (null = no rows yet). */
  prevFirstRowId: number | null;
  /** The window's first rowId of this commit (null = the rows were cleared). */
  nextFirstRowId: number | null;
  /** The virtual list's total height of the previous commit. */
  prevTotalSize: number;
  /** The virtual list's total height of this commit. */
  nextTotalSize: number;
}

/**
 * The scrollTop shift after a prepend. A positive shift is returned only when "the first row's
 * rowId got smaller" (a true prepend); append / replace / clear / first frame are all null (leave
 * the scroll position alone and let the bottom anchoring logic handle it).
 */
export function prependScrollAdjustment(input: PrependAnchorInput): number | null {
  if (input.prevFirstRowId === null || input.nextFirstRowId === null) {
    return null;
  }
  if (input.nextFirstRowId >= input.prevFirstRowId) return null;
  const delta = input.nextTotalSize - input.prevTotalSize;
  return delta > 0 ? delta : null;
}

/**
 * Top trigger threshold: a distance from the top below it counts as "at the top" and automatically
 * fetches an earlier window.
 */
const LOAD_OLDER_TRIGGER_PX = 64;

/**
 * Prefetch two viewports ahead, so the network and rendering finish before the user reaches the
 * window boundary.
 */
const LOAD_OLDER_PREFETCH_VIEWPORTS = 2;

export function historyPrefetchTriggerPx(viewportHeight: number): number {
  if (!Number.isFinite(viewportHeight) || viewportHeight <= 0) {
    return LOAD_OLDER_TRIGGER_PX;
  }
  return Math.max(LOAD_OLDER_TRIGGER_PX, viewportHeight * LOAD_OLDER_PREFETCH_VIEWPORTS);
}

/**
 * Whether a scroll event should trigger loadOlder (at the top + fetchable + not already in flight).
 */
export function shouldTriggerLoadOlder(input: {
  scrollTop: number;
  canLoadOlder: boolean;
  loadingOlder: boolean;
  triggerPx?: number;
}): boolean {
  return (
    input.canLoadOlder &&
    !input.loadingOlder &&
    input.scrollTop <= (input.triggerPx ?? LOAD_OLDER_TRIGGER_PX)
  );
}
