/**
 * Hidden subcommand `__zcode-dwf-child <entry path>`: the sandboxed child process entry point for dynamic workflows.
 *
 * Why it exists: a SEA single-file binary **does not interpret Node CLI flags** -- the flags in the harness's default
 * `node --max-old-space-size=… <entry>` fall straight through into the CLI's strict parseArgs, the child errors out and
 * exits immediately, so under SEA every workflow run necessarily fails. The fix is the same one as for the official plugin host
 * (`plugin-host-command.ts`): under SEA, bootstrap has the harness re-exec this binary with this subcommand, and
 * `run.ts` dispatches here **before** parseArgs.
 *
 * The payload no longer travels over argv (the Windows command line limit is
 * 32,767 characters); the harness writes a self-contained entry file `<cwd>/.zcode/workflow-runs/<runId>.mjs`, and the last argv
 * element is just its path. The entry file carries childMain and the payload itself, so here we only `import()` it and inject the CLI process's
 * vm/readline/stdio into the `start` it exports -- this module therefore **no longer depends on `@zcode/dynamic-workflow-runtime`**.
 * The best-effort `v8.setFlagsFromString` for the heap cap moved into the entry file together with the payload.
 */

import { resolve } from "node:path";
import { createInterface } from "node:readline";
import { pathToFileURL } from "node:url";
import { createContext, runInContext } from "node:vm";
import { ZCODE_DWF_CHILD_COMMAND } from "@zcode/contracts";
import type { RunContext } from "@zcode/shared-types";

export function isDwfChildInvocation(argv: readonly string[]): boolean {
  return argv[0] === ZCODE_DWF_CHILD_COMMAND;
}

/** The export surface of the entry file (generated by `renderChildEntry` in child-source.ts). */
interface ChildEntryModule {
  start?: (deps: {
    vm: { createContext: typeof createContext; runInContext: typeof runInContext };
    createInterface: typeof createInterface;
    stdin: NodeJS.ReadableStream;
    stdout: { write(chunk: string): unknown };
  }) => Promise<void>;
}

/**
 * Runs the sandboxed child process until the script terminates. `argv` is the remaining arguments after the subcommand name was stripped, and the **last** element is the entry file path.
 *
 * It must await until termination before returning: the CLI entry arms a 1s exit watchdog after `run()` returns
 * (`scheduleCliExitWatchdog` in shutdown.ts), so returning early amounts to letting the watchdog kill the child process right after the run got going.
 */
export async function runDwfChildCommand(ctx: RunContext, argv: string[]): Promise<number> {
  const entryPath = argv[argv.length - 1];
  if (argv.length === 0 || entryPath === undefined) {
    ctx.stderr.write(`Usage: ${ZCODE_DWF_CHILD_COMMAND} <entry path>\n`);
    return 1;
  }

  try {
    // Dynamically import a copy of ESM on the disk (the same as the plugin-host-command.ts loading plugin entry). Entry file
    // You can determine by yourself that "it is not a process entry" (argv[1] is the subcommand name, not it) and it will not start automatically. Call start from here.
    const entry = (await import(pathToFileURL(resolve(entryPath)).href)) as ChildEntryModule;
    if (typeof entry.start !== "function") {
      throw new Error(`workflow entry file exports no start(): ${entryPath}`);
    }
    await entry.start({
      vm: { createContext, runInContext },
      createInterface,
      stdin: ctx.stdin,
      stdout: ctx.stdout,
    });
    return 0;
  } catch (error) {
    // stdout is the NDJSON channel of the parent process, and diagnosis can only go through stderr - the harness is attributed to the stderr of the child process
    // "Exit without completion" failure (child.on("close") in harness.ts).
    const message = error instanceof Error ? error.message : String(error);
    ctx.stderr.write(`Workflow child failed: ${message}\n`);
    return 1;
  }
}
