//! P4 — the generated TypeScript suffix table must never drift from the Rust source.
//!
//! The table in `crates/zcode-packaging/src/target.rs` is the only place the
//! `${os}-${arch}` -> napi-suffix mapping is allowed to exist. `loader.ts` used to carry
//! a hand-maintained copy of the same six rows; it now reads the generated constants.
//!
//! These tests live in an integration test rather than in `src/target.rs` because they
//! reach outside the crate to the repository checkout, which unit tests inside the crate
//! should not do.

use std::path::{Path, PathBuf};

/// The workspace root, derived from this crate's manifest location.
///
/// `CARGO_MANIFEST_DIR` is `packages/rust/crates/zcode-packaging`, so the repo root is
/// the fourth ancestor: crates -> rust -> packages -> <root>.
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(4)
        .expect("crates/zcode-packaging is four levels below the repo root")
        .to_path_buf()
}

fn generated_path() -> PathBuf {
    repo_root().join("packages/rust/src/native-targets.generated.ts")
}

/// The exact bytes `gen-targets` produces. Duplicated as a literal on purpose: the test
/// must fail if either the generator or the checked-in file drifts, and comparing the
/// tool against itself would not catch a change to both.
const EXPECTED: &str = r#"// GENERATED by `cargo run -p zcode-packaging -- gen-targets`. Do not edit by hand.
// Source of truth: packages/rust/crates/zcode-packaging/src/target.rs
//
// `cargo test -p zcode-packaging` regenerates this file and byte-compares, so a
// hand edit fails the test rather than silently drifting from the packager (spec P4).

export const NATIVE_PLATFORM_SUFFIXES = {
  "darwin-arm64": "darwin-arm64",
  "darwin-x64": "darwin-x64",
  "linux-arm64": "linux-arm64-gnu",
  "linux-x64": "linux-x64-gnu",
  "win32-arm64": "win32-arm64-msvc",
  "win32-x64": "win32-x64-msvc",
} as const;

export type NativePlatformKey = keyof typeof NATIVE_PLATFORM_SUFFIXES;

export const NATIVE_PLATFORM_KEYS = Object.keys(
  NATIVE_PLATFORM_SUFFIXES,
) as NativePlatformKey[];
"#;

#[test]
fn the_repo_root_derivation_lands_on_the_workspace() {
    // A wrong ancestor count silently points at `packages/`, which makes every other
    // test in this file fail with a confusing NotFound. Assert it directly.
    let root = repo_root();
    assert!(root.join("packages/rust/Cargo.toml").is_file(), "{:?}", root);
    assert!(root.join("package.json").is_file(), "{:?}", root);
}

#[test]
fn generated_suffix_table_is_committed_and_current() {
    let path = generated_path();
    let actual = std::fs::read_to_string(&path).unwrap_or_else(|error| {
        panic!(
            "cannot read {}: {error}\n  run: cargo run -p zcode-packaging -- gen-targets",
            path.display()
        )
    });
    assert_eq!(
        actual,
        EXPECTED,
        "{} is stale or hand-edited. Regenerate it with:\n  \
         cargo run -p zcode-packaging -- gen-targets",
        path.display()
    );
}

#[test]
fn generated_file_is_marked_as_generated() {
    let text = std::fs::read_to_string(generated_path()).expect("generated file");
    assert!(text.starts_with("// GENERATED"));
    assert!(
        text.contains("Do not edit by hand"),
        "the generated header must warn off manual edits"
    );
    assert!(
        text.contains("src/target.rs"),
        "the generated header must name the Rust source of truth"
    );
}

/// The Rust table and the TypeScript table are two renderings of one fact. If a target
/// were added to `target.rs` and the generated file were not regenerated, the test above
/// would already fail; this test additionally guards the *values*, so a wrong mapping
/// that was applied consistently to both files is still caught.
#[test]
fn suffix_values_match_the_rust_table() {
    let text = std::fs::read_to_string(generated_path()).expect("generated file");
    for (key, suffix) in [
        ("darwin-arm64", "darwin-arm64"),
        ("darwin-x64", "darwin-x64"),
        ("linux-arm64", "linux-arm64-gnu"),
        ("linux-x64", "linux-x64-gnu"),
        ("win32-arm64", "win32-arm64-msvc"),
        ("win32-x64", "win32-x64-msvc"),
    ] {
        let line = format!("  \"{key}\": \"{suffix}\",");
        assert!(
            text.contains(&line),
            "generated table is missing or has the wrong value for {key}: expected `{line}`"
        );
    }
}

/// `loader.ts` must consume the generated table rather than keeping its own switch.
/// If someone restores the hardcoded table, this test fails.
#[test]
fn loader_reads_the_generated_table_instead_of_a_switch() {
    let loader = repo_root().join("packages/rust/src/loader.ts");
    let text = std::fs::read_to_string(&loader).expect("loader.ts");
    assert!(
        text.contains("native-targets.generated"),
        "loader.ts must import NATIVE_PLATFORM_SUFFIXES from the generated module; \
         a hardcoded switch in loader.ts would be a second copy of the table (spec P4)"
    );
    // The old switch spelled the suffixes out one by one. None of those literals may
    // survive outside the generated file.
    for literal in [
        "\"linux-x64-gnu\"",
        "\"linux-arm64-gnu\"",
        "\"win32-x64-msvc\"",
        "\"win32-arm64-msvc\"",
    ] {
        assert!(
            !text.contains(literal),
            "loader.ts still hardcodes {literal}; the mapping lives in target.rs"
        );
    }
}
