//! input history family — SQL ported verbatim from
//! `adapters/src/storage/session-store/repositories/input-history.ts` (lines 14-107).

use super::{js_i64, js_null, js_str, Ctx, StoreError};
use crate::jsjson::JsValue;

/// Positional argument at `index` of a `{"v": [...]}` payload.
fn arg<'a>(v: &'a [JsValue], index: usize) -> Result<&'a JsValue, StoreError> {
  v
    .get(index)
    .ok_or_else(|| StoreError::op(format!("missing positional argument {}", index)))
}

/// Payload:
/// `{ id, projectID, sessionID: string|null, text, attachmentsJson: string|null, kind, timeCreated, limit }`
/// `id` and `timeCreated` are pre-generated by TS
/// (`input_${now.toString(36)}_${uuid}`, `input.time?.created ?? nowMs`);
/// `attachmentsJson` is TS `encodeJson(normalized)` (null when there are no
/// attachments); `limit` is TS's `INPUT_HISTORY_LIMIT` (100). Runs the legacy
/// insert then the retention trim — the batch transaction replaces legacy's
/// `begin immediate`/`commit` (input-history.ts:40-70). Result: `null`.
pub fn record_input_history(ctx: &Ctx, payload: &JsValue) -> Result<String, StoreError> {
  let id = super::req_str(payload, "id")?;
  let project_id = super::req_str(payload, "projectID")?;
  let session_id = super::opt_str(payload, "sessionID")?;
  let text = super::req_str(payload, "text")?;
  let attachments_json = super::opt_str(payload, "attachmentsJson")?;
  let kind = super::req_str(payload, "kind")?;
  let time_created = super::req_i64(payload, "timeCreated")?;
  let limit = super::req_i64(payload, "limit")?;

  super::execute(
    ctx,
    r#"
        insert into input_history (id, project_id, session_id, text, attachments, kind, time_created)
        values (?, ?, ?, ?, ?, ?, ?)
        "#,
    &[
      js_str(&id),
      js_str(&project_id),
      session_id.as_deref().map(js_str).unwrap_or_else(js_null),
      js_str(&text),
      attachments_json
        .as_deref()
        .map(js_str)
        .unwrap_or_else(js_null),
      js_str(&kind),
      js_i64(time_created),
    ],
  )?;
  super::execute(
    ctx,
    r#"
        delete from input_history
        where id not in (
          select id from input_history
          order by time_created desc, id desc
          limit ?
        )
        "#,
    &[js_i64(limit)],
  )?;
  Ok("null".to_string())
}

/// Payload: `{ "v": [projectID, skipCount] }` -> Result: 0/1 raw
/// `input_history` rows (legacy `.get` → `decodeInputHistoryRow` in TS).
pub fn recall_previous_input_history(ctx: &Ctx, payload: &JsValue) -> Result<String, StoreError> {
  let v = super::vlist(payload)?;
  let project_id = super::as_str(arg(v, 0)?, "projectID")?;
  let skip_count = arg(v, 1)?
    .as_i64()
    .ok_or_else(|| StoreError::op("expected integer at positional argument 1"))?;
  super::query_rows(
    ctx,
    r#"
      select * from input_history
      where project_id = ?
      order by time_created desc, id desc
      limit 1 offset ?
      "#,
    &[js_str(&project_id), js_i64(skip_count)],
  )
}
