import { randomUUID } from "node:crypto";
import {
  classifyDatabaseStartupError,
  canRetryDatabaseStartup,
  databaseStartupErrorDetails,
  databaseMigrationFactsSchema,
  type DatabaseStartupState,
  type DatabaseMigrationFacts,
  type StartupDiskSummary,
} from "@zcode/shared";

type Report = (
  phase: DatabaseStartupState["phase"],
  databasePhase?: DatabaseStartupState["databasePhase"],
  details?: { databaseId: string; migration?: DatabaseMigrationFacts; finalDatabase?: boolean },
) => void;

/** One startup owner per window. Failure only advances through an explicit retry; refreshes and duplicate requests never re-run SQL. */
export class DatabaseStartupCoordinator {
  private readonly baselines = new Map<string, string | null | undefined>();
  private readonly migrations = new Map<string, DatabaseMigrationFacts>();
  private running = false;
  private started = false;
  private state: DatabaseStartupState;
  constructor(
    private readonly options: {
      startupId?: string;
      prepare: (report: Report) => Promise<void>;
      publish: (state: DatabaseStartupState) => void;
    },
  ) {
    const now = Date.now();
    this.state = {
      schemaVersion: 1,
      startupId: options.startupId ?? randomUUID(),
      attemptId: randomUUID(),
      sequence: 0,
      startedAt: now,
      updatedAt: now,
      phase: "starting",
      disk: [],
    };
  }
  get snapshot(): DatabaseStartupState {
    return structuredClone(this.state);
  }
  publish(): void {
    try {
      this.options.publish(this.snapshot);
    } catch {
      /* Notification failures cannot change the results of database execution. */
    }
  }
  updateDisk(disk: StartupDiskSummary[]): void {
    this.state = { ...this.state, disk, sequence: this.state.sequence + 1, updatedAt: Date.now() };
    this.publish();
  }
  async start(): Promise<void> {
    if (this.started) return;
    this.started = true;
    await this.run();
  }
  async retry(attemptId: string): Promise<void> {
    if (this.running || !canRetryDatabaseStartup(this.state) || attemptId !== this.state.attemptId)
      return;
    this.migrations.clear();
    this.baselines.clear();
    this.state = {
      ...this.state,
      migration: undefined,
      currentMigration: undefined,
      migrationBaselines: undefined,
      finalDatabase: undefined,
      attemptId: randomUUID(),
      startedAt: Date.now(),
      phase: "starting",
      errorCode: undefined,
      sqliteCode: undefined,
      systemCode: undefined,
      migrationId: undefined,
      failedPhase: undefined,
      databasePhase: undefined,
      disk: [],
    };
    await this.run();
  }
  private async run(): Promise<void> {
    this.running = true;
    const report: Report = (phase, databasePhase, details) => {
      if (details) {
        // Only the value in the trusted lock for the first time can replace unknown; subsequent factual notifications cannot erase the starting point.
        if (
          !this.baselines.has(details.databaseId) ||
          this.baselines.get(details.databaseId) === undefined
        )
          this.baselines.set(details.databaseId, details.migration?.lastAppliedMigrationId);
      }
      if (details?.migration) {
        const previous = this.migrations.get(details.databaseId);
        const next = details.migration;
        // The pre-inspection may find that the migration and lock acquisition are completed by other executors; the requirements are not lost, and the execution/submission is not inflated.
        const kind =
          previous?.kind === "upgrade" || next.kind === "upgrade"
            ? "upgrade"
            : previous?.kind === "initialize" || next.kind === "initialize"
              ? "initialize"
              : "none";
        this.migrations.set(details.databaseId, { ...next, kind });
      }
      const migration = this.migrations.size
        ? [...this.migrations.values()].reduce<DatabaseMigrationFacts>(
            (sum, facts) => ({
              kind:
                sum.kind === "upgrade" || facts.kind === "upgrade"
                  ? "upgrade"
                  : sum.kind === "initialize" || facts.kind === "initialize"
                    ? "initialize"
                    : "none",
              executedCount: sum.executedCount + facts.executedCount,
              committedCount: sum.committedCount + facts.committedCount,
            }),
            { kind: "none", executedCount: 0, committedCount: 0 },
          )
        : undefined;
      this.state = {
        ...this.state,
        phase,
        databasePhase,
        migration,
        // tasks-index is a fixed internal ID, and the session library ID is generated by the CLI hashing the real path.
        migrationBaselines: [...this.baselines].map(([databaseId, lastAppliedMigrationId]) => ({
          databaseId,
          databaseKind: databaseId === "tasks-index" ? "tasks-index" : "session",
          lastAppliedMigrationId,
        })),
        currentMigration: details?.migration,
        finalDatabase: details?.finalDatabase,
        sequence: this.state.sequence + 1,
        updatedAt: Date.now(),
      };
      this.publish();
    };
    report("starting");
    try {
      await this.options.prepare(report);
      report("ready");
    } catch (error) {
      this.state = {
        ...this.state,
        failedPhase: this.state.phase,
        errorCode: classifyDatabaseStartupError(error),
        ...databaseStartupErrorDetails(error),
      };
      const update = (
        error as { migrationUpdate?: { databaseId?: unknown; migration?: unknown } } | null
      )?.migrationUpdate;
      const facts = databaseMigrationFactsSchema.safeParse(update?.migration);
      report(
        "failed",
        undefined,
        facts.success && typeof update?.databaseId === "string"
          ? { databaseId: update.databaseId, migration: facts.data }
          : undefined,
      );
    } finally {
      this.running = false;
    }
  }
}
