/* Per-request dynamic identity header injection and failure classification for the official Server MCP.
 *
 *This is the single credential egress: it wraps the fetch obtained from createMcpTransportFetch and injects after the SDK has assembled
 *_commonHeaders() and requestInit but before the request is actually sent. Therefore all existing HTTP proxy,
 *custom CA and No Proxy policies are preserved — this wrapper only wraps it, it does not bypass it.
 */
import {
  findOfficialMcpReservedHeaders,
  isOfficialMcpReservedHeaderName,
  summarizeOfficialMcpIdentityHeaders,
  type McpServerFailureKind,
  type OfficialMcpAuthFailureKind,
} from "@zcode/shared";
import type {
  Logger,
  McpOfficialProvenance,
  OfficialMcpAuthHeadersPort,
  OfficialMcpTrustedOriginRegistry,
} from "@zcode/contracts";

/** An official auth error with a stable classification, thrown by the adapter. Callers must not route on the message text. */
export class OfficialMcpAuthError extends Error {
  constructor(
    readonly kind: OfficialMcpAuthFailureKind,
    message: string,
  ) {
    super(message);
    this.name = "OfficialMcpAuthError";
  }
}

/**
 * The header names used for correlation ids.
 *
 * They have two uses, neither of which is **sending**:
 * 1. Strip them from the request headers, so a plugin's static config cannot inject these two observability channels into the official endpoint;
 * 2. Read the request id generated by the server itself out of the **response headers**, and record it in the log for end-to-end reconciliation.
 *
 * The client never sends these two headers: the server always generates the request id itself and never reads an inbound value, so nothing would ever read them.
 */
const REQUEST_ID_HEADER = "x-request-id";
const TRACE_ID_HEADER = "x-trace-id";

interface CreateOfficialMcpAuthFetchInput {
  authHeadersPort?: OfficialMcpAuthHeadersPort;
  baseFetch: typeof globalThis.fetch;
  logger?: Logger;
  /**
   * The classification reporting hook. The SDK's version negotiation rewraps the OfficialMcpAuthError thrown by this module
   * into a plain Error (the message is preserved, the object identity is lost), so `instanceof` is unreliable upstream.
   * The classification must be reported at the throw site and cannot rely on upstream parsing of the error text (project rules forbid routing on error text).
   */
  onAuthFailure?: (kind: OfficialMcpAuthFailureKind) => void;
  /**
   * The reporting hook for the server's request id, used to correlate it back to one specific `tools/call`.
   *
   * Only this layer can see the response headers: above the wrapper sits the MCP SDK, which hands only the JSON-RPC result to the adapter.
   * So for an in-band failure (HTTP 200 + `isError: true`, such as an exhausted quota) to carry a request id,
   * it has to be emitted from here and then correlated by span in the adapter.
   */
  onServerResponse?: (response: OfficialMcpServerResponseInfo) => void;
  official: McpOfficialProvenance;
  serverName: string;
  trustedOrigins: OfficialMcpTrustedOriginRegistry;
  /** The MCP endpoint URL; Origin validation follows the actual URL of each request and is not done once at connect time. */
  url: string;
  workspaceIdentity?: string;
  workspacePath?: string;
}

/** The non-sensitive facts of one official MCP response that can be used for correlation. No body, no header values at all. */
export interface OfficialMcpServerResponseInfo {
  failureKind?: McpServerFailureKind;
  httpStatus: number;
  rpcMethod?: string;
  rpcToolName?: string;
  /** The server-generated `x-request-id`; absent when there is no HTTP response, and never fabricated. */
  serverRequestId?: string;
  /** The tool call span that issued this request. The adapter uses it to correlate the request id back to one specific call. */
  spanId?: string;
  traceId?: string;
}

/**
 * Re-resolves the identity headers and injects them before every trusted-Origin request; only a resolution failure degrades to anonymous.
 *
 * The semantics that matter:
 * - Origin is validated per request. The SDK may issue several kinds of requests over the same transport during a session,
 *   and validating only once at connect time would leave a gap for later URL changes;
 * - the reserved headers use set-overwrite semantics. append would produce a comma-joined multi-value Authorization,
 *   and "fill in only when missing" would let an unexpected pre-existing value survive (for example the OAuth token written by authProvider);
 * - redirect: "manual", so a 3xx fails outright, preventing the Bearer Token from being carried along by a cross-Origin redirect;
 * - only a request that actually had credentials injected is retried once after a 401; 403/3xx are never retried.
 */
export function createOfficialMcpAuthFetch(
  input: CreateOfficialMcpAuthFetchInput,
): typeof globalThis.fetch {
  const expectedOrigin = safeOrigin(input.url);

  /**
   * Reports the classification and builds the error, for the call site to `throw`.
   * Not thrown right here: an arrow function returning never does not trigger TS control-flow narrowing
   * (that would need an explicit type annotation on the call target), which would leave origin / resolved after the throw still a union type.
   */
  const failWith = (kind: OfficialMcpAuthFailureKind, message: string): OfficialMcpAuthError => {
    input.onAuthFailure?.(kind);
    return new OfficialMcpAuthError(kind, message);
  };

  const authFetch = async (
    resource: Parameters<typeof globalThis.fetch>[0],
    init?: Parameters<typeof globalThis.fetch>[1],
  ): Promise<Response> => {
    const requestUrl = resolveRequestUrl(resource);
    const origin = safeOrigin(requestUrl);
    if (!origin || !expectedOrigin || origin !== expectedOrigin) {
      throw failWith(
        "official_mcp_origin_untrusted",
        `official MCP request origin does not match the configured endpoint: ${input.serverName}`,
      );
    }
    const trust = await input.trustedOrigins.isTrusted({
      mcpKey: input.official.mcpKey,
      origin,
      pluginId: input.official.pluginId,
    });
    if (!trust.trusted) {
      // fail closed: The number of network requests must be 0, and the credentials will not be parsed.
      // Bring origin and pluginId in the message: When only serverName is reported, you cannot judge even if you see detail.
      // Determine what the input is (this caused the pluginId suffix issue to be mistaken for a url configuration issue).
      throw failWith(
        "official_mcp_origin_untrusted",
        `official MCP origin is not trusted (${trust.detail ?? "unknown"}): ` +
          `${input.serverName} origin=${origin} pluginId=${input.official.pluginId}`,
      );
    }

    // Request-level debug context. Deliberately only contains non-sensitive items: rpc method name, request body number of bytes, path.
    // The body content (including user query) is not recorded, and any header value is not recorded.
    const rpc = describeJsonRpc(init?.body);
    const logBase = {
      event: "mcp.official_auth.request",
      mcpKey: input.official.mcpKey,
      mcpServerName: input.serverName,
      module: "adapters.mcp.official_auth",
      requestBodyBytes: byteLength(init?.body),
      urlPath: safePath(requestUrl),
      ...(rpc.method ? { rpcMethod: rpc.method } : {}),
      ...(rpc.id !== undefined ? { rpcId: rpc.id } : {}),
      ...(rpc.toolName ? { rpcToolName: rpc.toolName } : {}),
      ...(rpc.traceId ? { mcpTraceId: rpc.traceId } : {}),
    };

    const send = async (attempt: number): Promise<{ authApplied: boolean; response: Response }> => {
      let authHeaders: Record<string, string> = {};
      let resolveDurationMs: number | undefined;
      if (input.authHeadersPort) {
        const resolveStartedAt = Date.now();
        const resolved = await input.authHeadersPort.resolveHeaders({
          mcpKey: input.official.mcpKey,
          pluginId: input.official.pluginId,
          targetOrigin: origin,
          ...(input.workspaceIdentity ? { workspaceIdentity: input.workspaceIdentity } : {}),
          ...(input.workspacePath ? { workspacePath: input.workspacePath } : {}),
          ...(init?.signal ? { signal: init.signal } : {}),
        });
        resolveDurationMs = Date.now() - resolveStartedAt;
        if (resolved.ok) {
          authHeaders = resolved.headers;
        } else {
          // When the identity cannot be resolved, the non-identity request is still handed over to the server for authoritative determination; the adapter does not cache old credentials.
          // Nor is it possible to pass off parsing failures locally as network failures.
          input.logger?.warn("Official MCP auth headers unavailable for request", {
            ...logBase,
            attempt,
            event: "mcp.official_auth.resolve",
            fallback: "anonymous",
            reason: resolved.reason,
            resolveDurationMs,
            status: "failed",
          });
        }
      } else {
        input.logger?.warn("Official MCP auth port unavailable for request", {
          ...logBase,
          attempt,
          event: "mcp.official_auth.resolve",
          fallback: "anonymous",
          reason: "official_auth_unavailable",
          status: "failed",
        });
      }
      // Only the header name and package dimensions are recorded, never the header value. targetType is PERSONAL/TEAM such
      // It is a low-sensitivity enumeration, but it is the most critical to "Why does the server judge that I have no rights?", so the original value is retained.
      const identity = summarizeOfficialMcpIdentityHeaders(authHeaders);
      const headers = mergeOfficialAuthHeaders(init?.headers, authHeaders);

      // The associated ID will never be sent out, only stripped.
      //
      // The server will not use the request id passed in by the client, it will always generate it by itself and will not read the inbound header.
      // So the client sends
      // X-Request-Id / X-Trace-Id will not be read by anyone, it is dead code and will mislead newcomers.
      //
      // The end-to-end reconciliation is changed to the opposite direction: read the x-request-id in the **response header** of the server and record it in the log
      // (See serverRequestId below), use it to check server logs.
      //
      // Still delete explicitly rather than letting it go: these two headers semantically belong to the associative/observable channel and should not be used by
      // The static configuration of the plug-in is injected into the official endpoint - the value set by the plug-in will appear in the server and middle layer logs as it is.
      headers.delete(REQUEST_ID_HEADER);
      headers.delete(TRACE_ID_HEADER);

      input.logger?.debug("Official MCP request sending", {
        ...logBase,
        attempt,
        resolveDurationMs,
        status: "started",
        timeoutHint: describeAbortSignal(init?.signal),
        ...identity,
      });

      const sendStartedAt = Date.now();
      try {
        const response = await input.baseFetch(resource, {
          ...init,
          headers,
          // The first phase does not follow any redirects; the official endpoint should be configured as a canonical URL.
          redirect: "manual",
        });
        // The request id generated by the server itself is read back from the response header. This is the **only** way to combine client logs with
        // Key on server log pair: The client does not send this header, and the server does not accept the inbound value.
        const serverRequestId = readServerRequestId(response);
        // Settings only consumes connection, initialize and tools/list diagnostics. tools/call may return large media,
        // The request id has been projected to the tool result by span, and it is prohibited to clone/read the response body in order to set the page.
        const failureKind =
          rpc.method === "tools/call" ? undefined : await classifyOfficialMcpResponse(response);
        if (serverRequestId || failureKind) {
          // Report to adapter for association. Place before the log: Even if the log level filters out both records,
          // If in-band fails, you can still get this id.
          input.onServerResponse?.({
            httpStatus: response.status,
            ...(failureKind ? { failureKind } : {}),
            ...(serverRequestId ? { serverRequestId } : {}),
            ...(rpc.method ? { rpcMethod: rpc.method } : {}),
            ...(rpc.toolName ? { rpcToolName: rpc.toolName } : {}),
            ...(rpc.spanId ? { spanId: rpc.spanId } : {}),
            ...(rpc.traceId ? { traceId: rpc.traceId } : {}),
          });
        }
        const outcome = {
          ...logBase,
          attempt,
          httpStatus: response.status,
          responseBodyBytes: numericHeader(response.headers.get("content-length")),
          sendDurationMs: Date.now() - sendStartedAt,
          ...(serverRequestId ? { serverRequestId } : {}),
        };
        if (response.ok) {
          input.logger?.debug("Official MCP response received", {
            ...outcome,
            status: "completed",
          });
        } else {
          // Non-2xx must be recorded in warn, not just the above debug.
          //
          // The lowest level of the logger for production builds is Info (see logging/index.ts
          // getDefaultMinLevel), debug is discarded directly. It turns out that when something goes wrong - precisely the only thing that needs to be reconciled
          // At that time - the server request id does not exist in the log at all, and can only be deduced by reading the code (3001
          // "parameter error" (that's what happened during the troubleshooting).
          //
          // Here we deliberately do not swallow the response: 4xx/5xx will still be returned to the SDK as it is, and it will report errors according to the protocol. This wrapper only
          // Add a searchable record. Classification failures of 401/403/3xx are thrown separately below.
          input.logger?.warn("Official MCP response failed", {
            ...outcome,
            status: "failed",
          });
        }
        return { authApplied: Object.keys(authHeaders).length > 0, response };
      } catch (error) {
        // Timeouts/cancellations appear here as AbortErrors. Distinguishing the two is key to determining "who cut it off":
        // Both upper-layer tool timeout budget expiration and user cancellation will result in abort, but the relationship between elapsed and budget is different.
        const sendDurationMs = Date.now() - sendStartedAt;
        input.logger?.warn("Official MCP request did not complete", {
          ...logBase,
          aborted: isAbortError(error),
          attempt,
          error: error instanceof Error ? error.message : String(error),
          errorName: error instanceof Error ? error.name : "unknown",
          sendDurationMs,
          status: "failed",
        });
        throw error;
      }
    };

    let sent = await send(1);
    let response = sent.response;
    if (response.status === 401 && sent.authApplied) {
      // Retry at most once, unconditionally. The only narrow race condition that can be self-healed by retrying is "the credentials happen to be refreshed after the request is sent";
      // The upper limit is 1, and there is no possibility of spin.
      input.logger?.info("Official MCP retrying once after 401", {
        ...logBase,
        attempt: 2,
        status: "started",
      });
      await discardBody(response);
      sent = await send(2);
      response = sent.response;
    }

    if (response.status === 401) {
      const baseMessage = "official MCP rejected the current credential";
      const message =
        rpc.method === "tools/call" ? withServerRequestId(baseMessage, response) : baseMessage;
      await discardBody(response);
      throw failWith("official_auth_rejected", message);
    }
    if (response.status === 403) {
      // The identity is valid but the permissions/package are insufficient. Retrieving the same certificate will not change the result.
      const baseMessage = "official MCP denied access for the current plan";
      const message =
        rpc.method === "tools/call" ? withServerRequestId(baseMessage, response) : baseMessage;
      await discardBody(response);
      throw failWith("official_auth_forbidden", message);
    }
    if (isRedirect(response.status)) {
      const baseMessage = `official MCP responded with a blocked redirect (${response.status})`;
      const message =
        rpc.method === "tools/call" ? withServerRequestId(baseMessage, response) : baseMessage;
      await discardBody(response);
      throw failWith("official_auth_redirect_blocked", message);
    }
    return response;
  };

  return authFetch as typeof globalThis.fetch;
}

const MAX_DIAGNOSTIC_RESPONSE_BYTES = 64 * 1024;

async function classifyOfficialMcpResponse(
  response: Response,
): Promise<McpServerFailureKind | undefined> {
  if (response.status === 429) return "rate_limited";
  if (response.status >= 500) return "server_internal_error";

  const contentType = response.headers.get("content-type")?.toLowerCase() ?? "";
  if (!contentType.includes("json")) {
    return response.ok ? undefined : "connection_failed";
  }
  const text = await readBoundedResponseText(response, MAX_DIAGNOSTIC_RESPONSE_BYTES);
  if (!text) return response.ok ? undefined : "connection_failed";
  try {
    const parsed: unknown = JSON.parse(text);
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      return response.ok ? undefined : "connection_failed";
    }
    const record = parsed as Record<string, unknown>;
    if (record["code"] === 3001) return "server_not_found";
    if (record["code"] === 1000) return "server_unavailable";
    if (record["jsonrpc"] === "2.0" && record["error"] !== undefined) {
      const rpcError = record["error"];
      if (rpcError && typeof rpcError === "object" && !Array.isArray(rpcError)) {
        const code = (rpcError as Record<string, unknown>)["code"];
        if (code === 1006) return "not_authenticated";
        if (code === 3101) return "coding_plan_required";
      }
      return "protocol_error";
    }
  } catch {
    return response.ok ? undefined : "connection_failed";
  }
  return response.ok ? undefined : "connection_failed";
}

async function readBoundedResponseText(
  response: Response,
  maxBytes: number,
): Promise<string | undefined> {
  const declaredLength = numericHeader(response.headers.get("content-length"));
  if (declaredLength !== undefined && declaredLength > maxBytes) return undefined;
  const body = response.clone().body;
  if (!body) return undefined;
  const reader = body.getReader();
  const decoder = new TextDecoder();
  let total = 0;
  let text = "";
  try {
    while (true) {
      const chunk = await reader.read();
      if (chunk.done) break;
      total += chunk.value.byteLength;
      if (total > maxBytes) {
        await reader.cancel();
        return undefined;
      }
      text += decoder.decode(chunk.value, { stream: true });
    }
    text += decoder.decode();
    return text;
  } finally {
    reader.releaseLock();
  }
}

/**
 * Merges static headers with identity headers. Identity headers always overwrite (set), and reserved headers
 * left over on the source side are stripped — static reserved headers were already blocked at parse time,
 * so this is the merge point's second enforcement.
 * Does not touch mcp-session-id / mcp-protocol-version / accept / content-type.
 */
function mergeOfficialAuthHeaders(
  incoming: HeadersInit | undefined,
  authHeaders: Record<string, string>,
): Headers {
  const merged = new Headers();
  const authHeaderNames = new Set(Object.keys(authHeaders).map((name) => name.toLowerCase()));
  new Headers(incoming ?? {}).forEach((value, name) => {
    const normalized = name.toLowerCase();
    // The identity header is written uniformly later; the remaining reserved headers (such as Authorization written by authProvider) are discarded directly.
    if (authHeaderNames.has(normalized)) return;
    if (
      isOfficialMcpReservedHeaderName(normalized) &&
      normalized !== "mcp-session-id" &&
      normalized !== "mcp-protocol-version"
    ) {
      return;
    }
    merged.set(name, value);
  });
  for (const [name, value] of Object.entries(authHeaders)) {
    merged.set(name, value);
  }
  return merged;
}

/** For the adapter to reuse when parsing config, so the blacklist has one source in both the parse and the merge. */
export { findOfficialMcpReservedHeaders };

function resolveRequestUrl(resource: Parameters<typeof globalThis.fetch>[0]): string {
  if (typeof resource === "string") return resource;
  if (resource instanceof URL) return resource.toString();
  return resource.url;
}

function safeOrigin(value: string): string | undefined {
  try {
    const url = new URL(value);
    // The URL with the certificate and its origin are not on the same trust surface and are directly judged as untrustworthy.
    if (url.username !== "" || url.password !== "") return undefined;
    return url.origin;
  } catch {
    return undefined;
  }
}

function isRedirect(status: number): boolean {
  return status >= 300 && status < 400;
}

/** The request id the server echoes back in the response headers. Returns undefined when absent. */
function readServerRequestId(response: Response): string | undefined {
  const value = response.headers.get(REQUEST_ID_HEADER)?.trim();
  return value ? value : undefined;
}

/**
 * Appends the server request id to the message of a classified error.
 *
 * Tool call classification errors are shown straight to the user, in the compact `message - requestId` form. Connection-time request ids
 * are joined uniformly by the adapter's structured status diagnostic, so they are not duplicated across SDK wrapping.
 */
function withServerRequestId(message: string, response: Response): string {
  const requestId = readServerRequestId(response);
  return requestId ? `${message} - ${requestId}` : message;
}

/** The request path (without the query). The query may carry user content, so it is discarded. */
function safePath(value: string): string {
  try {
    return new URL(value).pathname;
  } catch {
    return "(unparsable)";
  }
}

function byteLength(body: unknown): number | undefined {
  if (typeof body === "string") return Buffer.byteLength(body, "utf8");
  if (body instanceof Uint8Array) return body.byteLength;
  return undefined;
}

function numericHeader(value: string | null): number | undefined {
  if (!value) return undefined;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : undefined;
}

/**
 * Extracts the **structural** fields of a JSON-RPC request body for correlation logging: method / id / the tool name of tools\_call /
 * the trace\_id in `_meta`.
 * Deliberately does not take `params.arguments` — that is user input (a search term, say), not part of the "less sensitive" category.
 *
 * trace\_id exists only on `tools/call`: `initialize` / `tools/list` are issued by the SDK during the connect phase
 * and carry no `_meta`, so those two requests have a request id but no trace id. That is expected, not a defect.
 */
function describeJsonRpc(body: unknown): {
  id?: number | string;
  method?: string;
  spanId?: string;
  toolName?: string;
  traceId?: string;
} {
  if (typeof body !== "string" || body.length === 0) return {};
  try {
    const parsed: unknown = JSON.parse(body);
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return {};
    const record = parsed as Record<string, unknown>;
    const method = typeof record.method === "string" ? record.method : undefined;
    const id =
      typeof record.id === "number" || typeof record.id === "string" ? record.id : undefined;
    const params = isPlainRecord(record.params) ? record.params : undefined;
    const toolName = params && typeof params.name === "string" ? params.name : undefined;
    // mcpRequestMeta writes trace on params._meta (with both flat keys and com.zcode/ namespace keys).
    const meta = params && isPlainRecord(params._meta) ? params._meta : undefined;
    const traceId = meta && typeof meta.trace_id === "string" ? meta.trace_id : undefined;
    // span is the granularity of "one tool call": traceId covers the entire top-level session, within the same session
    // Call it multiple times to share it, and use it for association will cause confusion.
    const spanId = meta && typeof meta.span_id === "string" ? meta.span_id : undefined;
    return {
      ...(id !== undefined ? { id } : {}),
      ...(method ? { method } : {}),
      ...(spanId ? { spanId } : {}),
      ...(toolName ? { toolName } : {}),
      ...(traceId ? { traceId } : {}),
    };
  } catch {
    return {};
  }
}

function isPlainRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * A **non-sensitive summary** of the identity headers: only the names, whether they are paired, and the targetType enum value.
 * Never prints the Authorization or api-key values, not even truncated ones — log retention periods are not under our control.
 */
function describeAbortSignal(signal: AbortSignal | null | undefined): string {
  if (!signal) return "none";
  return signal.aborted ? "already-aborted" : "armed";
}

function isAbortError(error: unknown): boolean {
  return error instanceof Error && (error.name === "AbortError" || error.name === "TimeoutError");
}

async function discardBody(response: Response): Promise<void> {
  try {
    await response.body?.cancel();
  } catch {
    // Failure to discard the body does not affect the classification conclusion.
  }
}
