export type CuaPermissionKind = "accessibility" | "screen_recording";

export interface OpenCuaPermissionOnboardingOptions {
  /** Opaque id generated by the Renderer for this call; closing this permission surface only cancels this one participant. */
  operationId?: string;
  initialPermission?: CuaPermissionKind;
  /** Permissions whose fresh state confirmation is still missing; main opens the matching settings page one by one and waits for the app to come back. */
  requiredPermissions?: CuaPermissionKind[];
}

export interface CuaAccessibilitySettingsResult {
  success: boolean;
  canceled?: boolean;
  /** Main-level onboarding session id; concurrent windows sharing the same Helper identity share the same id. */
  sessionId?: string;
  /** Only becomes true once every staged settings page has observed any ZCode window returning. */
  returnedFromSettings?: boolean;
  /**
   * A single main onboarding session may be joined by several windows. For each distinct renderer/host exactly one call gets true and is
   * responsible for restarting that host's Helper; repeat calls from the same renderer get false. Picking a single window globally is not
   * allowed, because every window has its own host/Helper and the processes started before authorization each need their own recovery.
   * undefined is the legacy shape from older mains and is treated as a single-window owner.
   */
  restartHelperAfterReturn?: boolean;
  error?: string;
}

/**
 * Result of the drag-to-prime helper step (the shape visible to the renderer).
 *
 * Note that `helperBundleFingerprint` is deliberately **not declared here**: it is the main-process in-memory cache's synchronous TOCTOU evidence
 * (before dragstart it is used to check that "the bytes have not changed since self-verification"), and exposing it across IPC to the renderer is
 * both useless and a wider attack surface. The main side carries that field in a separate `PrepareCuaHelperPermissionDragMainResult`,
 * which explicitly strips it before the IPC handler returns.
 */
export interface PrepareCuaHelperPermissionDragResult {
  success: boolean;
  error?: string;
  helperAppPath?: string;
  helperDisplayName?: string;
  helperBundleId?: string;
}
