/** The global cap on raw bytes for a single video input accepted by ZCode. */
export const VIDEO_INPUT_MAX_BYTES = 30 * 1024 * 1024;

export const MEDIA_BUDGET_CURRENT_IMAGE_TOO_LARGE_ERROR_CODE =
  "MEDIA_BUDGET_CURRENT_IMAGE_TOO_LARGE";
export const MEDIA_BUDGET_CURRENT_VIDEO_TOO_LARGE_ERROR_CODE =
  "MEDIA_BUDGET_CURRENT_VIDEO_TOO_LARGE";

export const MEDIA_BUDGET_CURRENT_ATTACHMENT_TOO_LARGE_ERROR_CODE =
  "MEDIA_BUDGET_CURRENT_ATTACHMENT_TOO_LARGE";
