/* oxlint-disable eslint(max-lines) -- The ZCode task projection types are currently maintained in a single file; new workspace events stay declared nearby for now. */
// ── Old protocol compatibility (transition period)─────────────────────────────
// The remaining 29 exports: workspace warm-up/workspace events, turn steer results, session binding/import,
// trace/input/query id factory function, ZCodeError, ZCodeTaskCreateResult, etc.
// Consumer: services old stack (zcodeAgentService/zcodeTaskServiceAdapter/zcodeTaskService),
// UI old store/projection. Star load-bearing type (ZCodeTaskMeta/ZCodeStreamEvent/ZCodeTaskSnapshot, etc.)
// zcode-task-types-core.ts has been migrated (survivor). This file has the same life cycle as the old task service group.
import { createUuid } from "./uuid.js";
import type {
  TaskRealtimeReason,
  TraceId,
  InputId,
  QueryId,
  ZCodeTaskGoal,
  ZCodeProvider,
  ZCodeConfigOption,
  ZCodeSlashCommand,
  ZCodeTaskMeta,
  ZCodeTaskRuntimeCommand,
  ZCodeTaskRuntimeCommandStatus,
  ZCodeTaskSnapshotBodyField,
  ZCodeTaskSnapshotToolField,
  ZCodeTaskSnapshotFileContentField,
  ZCodePersistedToolCall,
} from "./zcode-task-types-core.js";

/** Generates a traceId; the legacy function name is kept for existing callers, and the format matches the agent's UUID trace. */
export function generateTraceId(_taskId: string): TraceId {
  return createUuid();
}

/** Creates a ZCode session-level observation traceId; subsequent prompts only inherit it and never regenerate it. */
export function createSessionTraceId(): TraceId {
  return createUuid();
}

export function createInputId(): InputId {
  return createUuid();
}

export function createQueryId(): QueryId {
  return createUuid();
}

/** The fixed system group id that sessions generated by cron scheduled tasks fall into by default. */
export const CRON_DEFAULT_GROUP_ID = "zcode-default-group-cron";

/** The fixed system group id that already-dispatched off-peak task sessions fall into by default (isomorphic to the cron group). */
export const OFF_PEAK_DEFAULT_GROUP_ID = "zcode-default-group-off-peak";

type CronTaskIdentity = Pick<ZCodeTaskMeta, "cronAutomationId"> & {
  automationId?: string;
};

/** Determines whether a task/session was produced by a scheduled task trigger. */
export function isCronTask(task: CronTaskIdentity): boolean {
  // The persistent task meta uses cronAutomationId; but the field name in the running state dispatch/old link is automationId.
  // If the UI only looks at the former, newly created or newly restored scheduled tasks will temporarily have no icon.
  return Boolean(task.cronAutomationId || task.automationId);
}

/** Determines whether a task/phantom row belongs to an off-peak task (only looks at the persisted meta flag; the UI does not query back into the off-peak store). */
export function isOffPeakTask(task: Pick<ZCodeTaskMeta, "offPeakTaskId">): boolean {
  return Boolean(task.offPeakTaskId);
}

// ---- ZCode Provider ----
export type ZCodeTaskTarget = ZCodeTaskGoal;
// ---- ZCode task mode ----
// ---- ZCode runtime status ----

/** Workspace-level ZCode initialization status */
export type ZCodeWorkspaceInitStatus = "idle" | "initializing" | "ready" | "failed";

/** Result returned when warming up a workspace */
export interface ZCodeWorkspacePrepareResult {
  workspacePath: string;
  preparedSessionId: string;
  version?: string;
  provider: ZCodeProvider;
  /** The initial configOptions returned by session/new, pushed to the UI already during warmup so the user can pick a model in advance */
  configOptions?: ZCodeConfigOption[];
  /** The slash commands already broadcast by the warmup session, which the draft state can also display directly */
  slashCommands?: ZCodeSlashCommand[];
}

// ---- Task metadata ----

/** The return value of createTask; on top of the persisted metadata it adds the transient initialization data needed for the first-screen render. */
export interface ZCodeTaskCreateResult extends ZCodeTaskMeta {
  /** The first batch of slash commands, available already at createTask time, so the UI does not lose the initialization commands before its subscription is established. */
  initialSlashCommands?: ZCodeSlashCommand[];
}

/** The source provider of an imported external native session; decoupled from the agent runtime's ZCodeProvider, currently Claude Code only. */
export type ZCodeImportSessionSourceProvider = "claude";

/** An import candidate for an external native session. */
export interface ZCodeImportableSessionCandidate {
  provider: ZCodeImportSessionSourceProvider;
  sessionId: string;
  workspacePath: string;
  sourcePath: string;
  updatedAt: number;
  createdAt?: number;
  previewTitle?: string;
}

export interface ZCodeImportedSessionResultItem {
  provider: ZCodeImportSessionSourceProvider;
  sessionId: string;
  taskId: string;
  workspacePath: string;
}

export interface ZCodeImportedSessionSkippedItem {
  provider: ZCodeImportSessionSourceProvider;
  sessionId: string;
  reason: string;
  workspacePath?: string;
}

export interface ZCodeImportSessionsResult {
  imported: ZCodeImportedSessionResultItem[];
  skipped: ZCodeImportedSessionSkippedItem[];
  failed: ZCodeImportedSessionSkippedItem[];
}

// ---- ZCode configuration and command types ----
// ---- ZCode streaming event (Host → Renderer) ----
// ---- Added new streaming event type ----

export interface ZCodeEnqueueTaskCommandResult {
  accepted: true;
  command: ZCodeTaskRuntimeCommand;
}

export interface ZCodeCancelTaskCommandResult {
  canceled: boolean;
  commandId: string;
  status?: ZCodeTaskRuntimeCommandStatus;
  reason?: "not_found" | "already_running";
}

// ---- Workspace level events (warming phase, asynchronous notification before task creation) ----

/**
 * Workspace-level events, used to deliver in real time the notifications the ZCode Agent pushes
 * asynchronously (such as slash commands and configOptions) to the UI before a task is created.
 *
 * Difference from ZCodeStreamEvent: ZCodeStreamEvent is bound to a concrete taskId, while
 * ZCodeWorkspaceEvent is bound to workspacePath and covers the gap before a task is created.
 */
export type ZCodeWorkspaceEvent =
  | ZCodeWorkspaceSlashCommandsUpdate
  | ZCodeWorkspaceConfigOptionsUpdate
  | ZCodeWorkspaceTaskListChanged
  | ZCodeWorkspaceSessionMessageSendRequested;

export interface ZCodeWorkspaceSlashCommandsUpdate {
  type: "workspace_slash_commands_update";
  workspacePath: string;
  /**
   * The `/` commands of a remote workspace are identity-isolated state and cannot be dispatched on
   * workspacePath alone. The same path may come from different SSH/WSL sessions, so with
   * workspaceIdentity attached the service/UI can converge on workspaceKey.
   */
  workspaceIdentity?: string;
  commands: ZCodeSlashCommand[];
}

export interface ZCodeWorkspaceConfigOptionsUpdate {
  type: "workspace_config_options_update";
  workspacePath: string;
  /**
   * Warmup configuration is likewise workspace-level identity state, so the remote scenario must carry workspaceIdentity along with the event.
   */
  workspaceIdentity?: string;
  configOptions: ZCodeConfigOption[];
}

export interface ZCodeWorkspaceTaskListChanged {
  type: "workspace_task_list_changed";
  workspacePath: string;
  workspaceIdentity?: string;
  taskId?: string;
  reason: "auto_archive" | "realtime_sync" | TaskRealtimeReason;
  taskMeta?: ZCodeTaskMeta;
  /** The Host has confirmed that this terminal state should produce a background unread; ordinary status/resume/snapshot convergence must not carry it. */
  unreadSignal?: "background_terminal";
}

export interface ZCodeWorkspaceSessionMessageSendRequested {
  type: "workspace_session_message_send_requested";
  workspacePath: string;
  workspaceIdentity?: string;
  request: {
    content: string;
    createdAt: string;
    fromSessionId: string;
    messageId: string;
    requestId: string;
    toSessionId: string;
  };
}

// ---- Error ----

export interface ZCodeError {
  code: string;
  message: string;
  traceId?: TraceId;
  taskId?: string;
}

// ---- Persistence format ----

export interface ZCodeTaskSnapshotBody {
  refId: string;
  field: ZCodeTaskSnapshotBodyField;
  content: string;
  hash: string;
  fullBytes: number;
}

export type ZCodeTaskSnapshotRefKind = "tool_field" | "file_change_field";

export interface ZCodeTaskSnapshotRefContent {
  kind: ZCodeTaskSnapshotRefKind;
  refId: string;
  field: ZCodeTaskSnapshotToolField | ZCodeTaskSnapshotFileContentField;
  content: unknown;
  hash: string;
  fullBytes: number;
}

export interface ZCodeTaskSnapshotToolCallsSlice {
  taskId: string;
  messageIndex: number;
  totalTools: number;
  startToolIndex: number;
  endToolIndexExclusive: number;
  tools: ZCodePersistedToolCall[];
}
