/**
 * TEMPORARY-GENERATOR: emits golden wire vectors from the REAL TypeScript RPC
 * implementation, so the Rust port can be asserted byte-for-byte against it.
 *
 * This file is the source of truth for `zcode-rpc-server`'s fixtures. Re-run it
 * whenever `packages/rpc` framing or serialization changes:
 *
 *   pnpm exec tsx scripts/gen-rpc-golden.ts > packages/rust/crates/zcode-rpc-server/tests/golden-vectors.json
 */
import {
  BufferReader,
  BufferWriter,
  serialize,
  deserialize,
} from "../packages/rpc/src/serialization.js";
import {
  ProtocolMessageType,
  writeProtocolMessage,
  ProtocolMessage,
} from "../packages/rpc/src/protocol.js";
import { VSBuffer } from "../packages/rpc/src/buffer.js";

const toHex = (buf: VSBuffer): string => Buffer.from(buf.buffer).toString("hex");

/** serialize() one value, exactly as the TS writer does. */
function ser(value: unknown): string {
  const w = new BufferWriter();
  serialize(w, value);
  return toHex(w.buffer);
}

/** Channel request envelope, mirroring ChannelClient.sendRequest. */
function request(requestType: number, id: number, channel: string, name: string, arg: unknown): string {
  const w = new BufferWriter();
  serialize(w, [requestType, id, channel, name]);
  serialize(w, arg);
  return toHex(w.buffer);
}

/**
 * Cancel/dispose envelope, mirroring `ChannelClient.sendCancelOrDispose`.
 *
 * Note this is a TWO element array, not the four element request header: the
 * real client sends `[type, id]` with no channel or method. Encoding four
 * elements here would record a shape the client never produces.
 */
function cancelOrDispose(type: number, id: number): string {
  const w = new BufferWriter();
  serialize(w, [type, id]);
  serialize(w, undefined);
  return toHex(w.buffer);
}

/** Channel response envelope, mirroring ChannelServer.send. */
function response(responseType: number, id: number | undefined, data: unknown): string {
  const w = new BufferWriter();
  if (id === undefined) serialize(w, [responseType]);
  else serialize(w, [responseType, id]);
  serialize(w, data);
  return toHex(w.buffer);
}

/** Wrap a payload in the 13-byte SocketProtocol header. */
function frame(payloadHex: string): string {
  const payload = VSBuffer.wrap(new Uint8Array(Buffer.from(payloadHex, "hex")));
  return toHex(
    writeProtocolMessage(new ProtocolMessage(ProtocolMessageType.Regular, 0, 0, payload)),
  );
}

const vectors: Record<string, unknown> = {
  _comment:
    "Generated by scripts/gen-rpc-golden.ts from packages/rpc. Do not hand-edit.",

  // --- Value serialization: [type tag][VQL len][data] -------------------------
  serialize: {
    undefined: ser(undefined),
    emptyString: ser(""),
    string: ser("hello"),
    unicode: ser("héllo→世界"),
    intZero: ser(0),
    intSmall: ser(127),
    intVqlBoundary: ser(128),
    intLarge: ser(300),
    intMax: ser(2147483647),
    boolFalse: ser(false),
    boolTrue: ser(true),
    null: ser(null),
    emptyArray: ser([]),
    array: ser([1, "two", false]),
    emptyObject: ser({}),
    object: ser({ a: 1, b: "two", c: [1, 2] }),
    nestedObject: ser({ outer: { inner: { deep: true } } }),
  },

  // --- Channel request envelopes --------------------------------------------
  requests: {
    // [RequestType.Promise=100, id, channelName, methodName] + arg
    promiseStringArg: request(100, 0, "setting", "get", "someKey"),
    promiseNoArg: request(100, 1, "system", "info", undefined),
    promiseObjectArg: request(100, 42, "git", "refresh", { workspacePath: "/tmp/x", recursive: true }),
    promiseArrayArg: request(100, 4294967295, "file", "read", ["/a", "/b", 3]),
    // [RequestType.EventListen=102, id, channelName, methodName] + arg
    eventListen: request(102, 7, "broadcast", "onMessage", undefined),
    eventListenWithArg: request(102, 8, "zcode-agent", "onDidChangeFrame", { limit: 20 }),
    // The positional-argument form. `ProxyChannel.toService` sends
    // `[...methodArgs]`, never the bare value, and `fromService` spreads it back
    // with `Function.apply`. A one-argument call is therefore an array holding
    // that one argument. Getting this wrong silently hands the handler an array
    // where it expects a value, so the form is pinned here.
    probeIntranetPositional: request(100, 13, "system", "probeIntranet", [
      {
        targets: [{ host: "127.0.0.1", port: 1, timeoutMs: 150 }],
        attempts: 1,
      },
    ]),
    zeroArgCall: request(100, 14, "system", "info", []),
    deepNestedArg: request(100, 12, "test", "deep", {
      a: { b: { c: [1, "two", false, null] } },
      d: [[1, 2], [3, 4]],
    }),
    // [RequestType.PromiseCancel=101, id] + undefined
    promiseCancel: cancelOrDispose(101, 5),
    // [RequestType.EventDispose=103, id] + undefined
    eventDispose: cancelOrDispose(103, 6),
  },

  // --- Channel response envelopes -------------------------------------------
  responses: {
    // [ResponseType.Initialize=200] + undefined
    initialize: response(200, undefined, undefined),
    promiseSuccess: response(201, 0, { ok: true }),
    promiseSuccessString: response(201, 1, "plain"),
    promiseSuccessUndefined: response(201, 2, undefined),
    promiseError: response(202, 3, { name: "Error", message: "boom", stack: ["a", "b"] }),
    promiseErrorObj: response(203, 4, { code: "X", detail: { nested: 1 } }),
    eventFire: response(204, 5, [{ id: "evt-1" }]),
  },

  // --- Transport framing (13-byte header + payload) -------------------------
  // The payload hex is recorded alongside each framed vector so a consumer can
  // rebuild the frame without having to know which request it was built from.
  framing: {
    smallPayload: frame(request(100, 0, "system", "info", undefined)),
    smallPayloadBody: request(100, 0, "system", "info", undefined),
    largerPayload: frame(request(100, 3, "file", "read", { path: "/some/longer/path/file.txt" })),
    largerPayloadBody: request(100, 3, "file", "read", { path: "/some/longer/path/file.txt" }),
    emptyPayload: frame(""),
    emptyPayloadBody: "",
  },
};

// Round-trip check: every generated vector must deserialize back to a value with
// the same structure, so we are not just recording bytes that the TS side cannot
// itself read back.
const roundTrip: Record<string, unknown> = {};
for (const [name, hex] of Object.entries(vectors.serialize as Record<string, string>)) {
  const reader = new BufferReader(VSBuffer.wrap(new Uint8Array(Buffer.from(hex, "hex"))));
  roundTrip[name] = deserialize(reader);
}
vectors._roundTripSerialize = roundTrip;

process.stdout.write(JSON.stringify(vectors, null, 2) + "\n");
