import type { ReactNode } from "react";
import type { WorkflowRunState } from "@zcode/shared/zcode-protocol-v4";
import type { MessageFileLinkTarget } from "@/components/ai-elements/message.js";
import type { CodePreviewSettings } from "@/lib/codePreviewSettings.js";
import type { CodeViewerSource } from "@/lib/codeViewer.js";
import { countPatchFileDiffs } from "@/lib/patchDiffPreview.js";
import type { TaskChatToolCallTreeNode } from "@/lib/toolCallTree.js";
import type { ToolDisplayModel } from "@/lib/toolDisplay.js";
import type { Theme } from "@/useTheme.js";
import type { OpenPlanDetailSideTabRequest } from "@/lib/workspaceSidePane.js";

export function isPlainRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function readStringField(
  value: Record<string, unknown>,
  keys: readonly string[],
): string | undefined {
  for (const key of keys) {
    const candidate = value[key];
    if (typeof candidate === "string" && candidate.trim().length > 0) {
      return candidate;
    }
  }

  return undefined;
}

export function readUnifiedDiffField(value: unknown): string | undefined {
  if (!isPlainRecord(value)) {
    return undefined;
  }

  return readStringField(value, ["unified_diff", "unifiedDiff", "patch", "diff"]);
}

export function normalizeSingleFilePatch(
  patch: string | undefined,
  fileLabel: string,
): string | undefined {
  if (!patch) {
    return undefined;
  }

  const trimmedPatch = patch.trim();
  if (!trimmedPatch) {
    return undefined;
  }

  if (countPatchFileDiffs(trimmedPatch) > 1) {
    // When sub-agent edits the same file for the second time, the tool layer sometimes returns multiple diff sections in the same field.
    // PatchDiff can only parse single-file patches. Direct rendering will throw an error and cause "click on the file name to view changes" to fail.
    // Here we first discard the multi-file patch and let the upper layer fall back to the single-file diff (or file content preview) generated by old/newText.
    return undefined;
  }

  if (/^---\s+/m.test(trimmedPatch) && /^\+\+\+\s+/m.test(trimmedPatch)) {
    return trimmedPatch;
  }

  if (trimmedPatch.startsWith("@@ ")) {
    const firstHeader = trimmedPatch.match(/^@@\s-(\d+)(?:,(\d+))?\s\+(\d+)(?:,(\d+))?\s@@/m);
    const deletedCount = Number(firstHeader?.[2] ?? firstHeader?.[1] ?? "1");
    const addedCount = Number(firstHeader?.[4] ?? firstHeader?.[3] ?? "1");

    // The unified_diff returned by the tool often only has the hunk fragment and no header.
    // For the "new file" scenario, if you continue to add --- a/file, PatchDiff will parse it as a normal change.
    // When a large file is added, it is easier to drag the page to death. Here, it is judged based on the first hunk whether it is a pure new addition, and the /dev/null header is added.
    return [
      deletedCount === 0 && addedCount > 0 ? "--- /dev/null" : `--- a/${fileLabel}`,
      addedCount === 0 && deletedCount > 0 ? "+++ /dev/null" : `+++ b/${fileLabel}`,
      trimmedPatch,
    ].join("\n");
  }

  // The apply_patch original may also contain @@, but it is not standard unified diff.
  // You cannot forcibly add the ---/+++ header to this type of content, otherwise the malformed patch will be sent to PatchDiff when summary opens the file.
  return trimmedPatch;
}

export function readRawToolCallInput(raw: unknown): unknown {
  if (!isPlainRecord(raw)) {
    return null;
  }

  if ("rawInput" in raw && raw.rawInput !== undefined) {
    return raw.rawInput;
  }

  // The permission/request payload of ZCode protocol puts the tool parameters in the input according to the schema.
  // The old UI is read-only compatible with the input field rawInput, and Write/Edit will be degraded to the entire JSON display instead of file diff.
  return "input" in raw ? raw.input : null;
}

export function readStructuredDiffBlock(
  value: unknown,
): { path?: string; oldText: string; newText: string } | null {
  if (!isPlainRecord(value) || value.type !== "diff" || typeof value.newText !== "string") {
    return null;
  }

  return {
    path: typeof value.path === "string" && value.path.trim() ? value.path : undefined,
    oldText:
      typeof value.oldText === "string"
        ? value.oldText
        : value.oldText == null
          ? ""
          : String(value.oldText),
    newText: value.newText,
  };
}

export function readRawToolCallChanges(raw: unknown) {
  if (!isPlainRecord(raw)) {
    return {
      directChanges: null,
      rawInputChanges: null,
      rawOutputChanges: null,
    };
  }

  const rawInputSource = readRawToolCallInput(raw);
  const rawInput = isPlainRecord(rawInputSource) ? rawInputSource : null;
  const rawOutput = isPlainRecord(raw.rawOutput) ? raw.rawOutput : null;

  return {
    directChanges: isPlainRecord(raw.changes) ? raw.changes : null,
    rawInputChanges: rawInput && isPlainRecord(rawInput.changes) ? rawInput.changes : null,
    rawOutputChanges: rawOutput && isPlainRecord(rawOutput.changes) ? rawOutput.changes : null,
  };
}

export interface RawToolCallFileSummary {
  path: string;
  actionLabel: "Created" | "Edited" | "Deleted";
  operationKind: EditOperationKind;
  fileName: string;
  filePath: string | null;
  fileIconSrc: string;
  changeStat?: { added: number; removed: number };
  patch?: string | null;
}

/**
 * All the workflow run facts the tool card in the chat area needs to render its run state. The host
 * computes them together when it joins the `workflowRuns` projection by `toolCallId`.
 *
 * Deliberately only these four fields: the card carries the **entry point and the summary**;
 * budget, event log, result, and failure panels all belong to the detail page.
 */
export interface WorkflowRunCardSummary {
  runId: string;
  /**
   * The id of the **CreateWorkflow row** that started this run (the projected `run.toolCallId`).
   * Any request that opens the side-pane run view must carry it — `WorkflowRunSidePane` uses this
   * id to look the starting row up in the row window (the causalityGraph and the script source text
   * both hang off that row). It is only populated in the byRunId join table (the key of the
   * byToolCallId table is this value); a resume row's own toolCallId is **not** this value (a
   * resume row's display has no graph).
   */
  toolCallId?: string;
  status: WorkflowRunState["status"];
  /** The reason for `stopped`; only carried when the projection carries it. */
  stopReason?: WorkflowRunState["stopReason"];
  /**
   * Number of settled nodes (`phase === "settled"`), **including** those that hit the cap and never
   * made it into the table.
   */
  nodesSettled: number;
  /**
   * Number of scheduled (observed) nodes, **not** an end-to-end total — for a dynamic workflow the
   * node count is decided by the script at run time, so no static total exists. Progress therefore
   * reads as "how many of the scheduled ones have settled", and never poses as a completion
   * percentage.
   *
   * Both numbers come from `workflowRunStepCounts` (@zcode/shared): the ones inside the `nodes`
   * table plus `usage.nodesUnlisted` for the ones outside it. A run that hit the 1024 cap still
   * reports its real step count here; what is missing is the **per-step detail**, which the card
   * and the detail page each call out with their own "details for only n/m steps" line.
   */
  nodesTotal: number;
  /**
   * Subagent count (the projected `run.actors.length`). The counts on the card cover only phases
   * and subagents.
   *
   * It is still optional: both join-table builders always fill it in, but the type does not require
   * it — once cold replay landed, the two journal-fallback merges were deleted, so today there is
   * no second producer; the consuming side stays tolerant of its absence and writes no count.
   */
  agents?: number;
  /**
   * This run in the live projection: the card builds its timeline model from it (lamps, pills,
   * ink). It is absent when the journal fallback hits — at that point only the status word exists,
   * so the timeline is drawn static.
   */
  run?: WorkflowRunState;
  /**
   * Resumable (a live projection `cancelled`, or a `resumable` that the journal summary computed
   * with the CLI's resume gate). The Resume in the card footer renders only when it is present; the
   * UI never derives it itself from status + failureCode.
   */
  resumable?: true;
}

/**
 * Where a CreateWorkflow / AmendWorkflow row sits in the compile-feedback loop. The host computes
 * it in one pass over the row window in row order (`v4/workflowDraftJoin.ts`); the renderer only
 * reads it.
 */
export interface WorkflowDraftPosition {
  /**
   * Which draft: within the same lineage and the same round, the nth submission since the last
   * compile, counting from 1.
   */
  ordinal: number;
  /**
   * When another row of the same lineage follows, the feedback row's empty ring lamp fades from the
   * warning color to a neutral one.
   */
  superseded: boolean;
}

export interface ToolCallBlockRenderContext {
  isOfficeMode?: boolean;
  toolCallNode: TaskChatToolCallTreeNode;
  workspacePath: string;
  /**
   * App theme (store decoupling): passed in from higher-level state by the host that builds the
   * render context (ToolCallBlock / PermissionDialog, etc.), for presentational components such as
   * MessageResponse / EditInlineDiffContent to route between light and dark. When absent,
   * presentational components fall back to "system".
   */
  theme?: Theme;
  /**
   * Code preview settings (store decoupling): same as above, passed in by the host with a stable
   * reference.
   */
  codePreviewSettings?: CodePreviewSettings;
  displayModel: ToolDisplayModel;
  viewerSource: CodeViewerSource | null;
  rawFileSummaries: RawToolCallFileSummary[];
  isRunning: boolean;
  statusLabel: string;
  sourceLabel?: string;
  errorText?: string;
  childToolList: ReactNode;
  showIcon?: boolean;
  /** CUA Group sub-items explicitly enlarge the App Icon; a standalone CUA keeps the default size. */
  cuaAppIconClassName?: "size-4" | "size-5";
  kindLabelOverride?: ReactNode;
  showTodoToolCalls?: boolean;
  disableSummaryContentAnimation?: boolean;
  /**
   * A Changes sub-item may mount only after the diff already exists, so the first number needs its
   * entrance animation too.
   */
  animateDiffCountOnMount?: boolean;
  canToggle?: boolean;
  forceOpen?: boolean;
  /**
   * Read-only observation entry point for a v4 subagent child session. The Agent renderer turns the
   * summary row into an action that opens the right-hand tab directly; non-Agent tools ignore it.
   */
  agentSummaryAction?: {
    onActivate: () => void;
    testId?: string;
  };
  /**
   * The authoritative runtime type projected by a paired v4 subagentRow; prefer it while the
   * streaming input is still incomplete.
   */
  authoritativeAgentType?: string;
  /**
   * ExitPlanMode plan card: opens the Side Pane once the conversation host has bound the
   * parent/session scope.
   */
  onOpenPlanDetail?: (request: Omit<OpenPlanDetailSideTabRequest, "parentSessionId">) => void;
  /**
   * Entry point to a CreateWorkflow run's details.
   *
   * The card only supplies the display name — `toolCallId`, `runId`, and the conversation identity
   * are all bound by the host. **Its very presence is the gate**: the host injects it only when
   * that tool call really has a run to open (the run identity comes from the `workflowRuns`
   * projection, see the comment on `workflowRunSchema.toolCallId`: it is the "tool card → detail
   * page" association key). It deliberately does not read `backgroundTaskId` out of the tool
   * output: a v4 row's `output.text` holds only the one `response` sentence that
   * `formatCreateWorkflowModelContent` picked out; the structured fields are not on the row.
   */
  onOpenWorkflowRun?: (request: { workflowName?: string; phaseId?: string }) => void;
  /**
   * Resume in the card footer: the same v4 `resumeWorkflowRun {workId}` command as on the detail
   * page, with the host binding the runId and the conversation. Absent means no button is rendered.
   */
  onResumeWorkflowRun?: (request: { workflowName?: string }) => void;
  /**
   * Clicking a subagent pill opens its transcript directly: the card hands over the slot identity
   * (run, site, ordinal, runtime name, plus the conversation id when there is one; a pill that has
   * not started yet can be opened too and lands on a placeholder tab), while the conversation and
   * workspace identities are bound by the host. Absent means the pill is not clickable.
   */
  onOpenWorkflowActor?: (request: {
    runId: string;
    actorSessionId?: string;
    siteId: string;
    ordinal: number;
    actorName?: string;
  }) => void;
  /**
   * Script pill → script transcript tab: the card only hands over this stop's stage id (the landing
   * spot) and display name; the run, the starting row, and the conversation identity are bound by
   * the host (same as `onOpenWorkflowRun`). Absent means the script pill is not clickable.
   */
  onOpenWorkflowWorkspace?: (request: { phaseId: string; workflowName?: string }) => void;
  /**
   * Artifact pill under the timeline → artifact tab: the card hands over only the artifact id; the
   * run and conversation identities are bound by the host. Absent means the pill is disabled.
   */
  onOpenWorkflowArtifact?: (artifactId: string) => void;
  /**
   * The workflow run summary this tool call has joined to; when present, the card enters its run
   * state (a compact, clickable card).
   *
   * The card does not go dig through the `workflowRuns` projection itself: the join (by
   * `toolCallId`) and the counts are all computed in one pass on the host side
   * (`workflowRunCardJoin.ts`), and the renderer only reads. `nodesTotal` is the number of
   * **scheduled** (observed) nodes — a dynamic workflow has no static total, so progress reads as
   * "how many of the scheduled ones have settled", not an end-to-end percentage.
   */
  workflowRun?: WorkflowRunCardSummary;
  /**
   * The draft position of this tool call; when absent (the host has no row window, as in a
   * read-only share) the card is not numbered and the lamp stays in the warning color. Like
   * `workflowRun` it is not passed down to sub-tool cards: the position is joined by toolCallId, so
   * handing it to a different row would hand over someone else's draft number.
   */
  workflowDraft?: WorkflowDraftPosition;
  onOpenCodeViewer?: (source: CodeViewerSource) => void;
  onOpenFileLink?: (target: MessageFileLinkTarget) => void;
  onOpenBrowserUrl?: (url: string) => void;
  /**
   * Scheduled-task tool card navigates to the management page; when an automationId is present it
   * opens the details directly.
   */
  onOpenAutomationsMain?: (automationId?: string) => void;
  onLoadFullToolCallFields?: (toolId: string) => Promise<boolean | void> | boolean | void;
}

export interface EditKindSource {
  toolName?: string | null;
  kind?: string | null;
  title?: string | null;
  input?: unknown;
  output?: unknown;
  raw?: unknown;
}

export type EditOperationKind = "write" | "edit" | "update" | "delete";
export type EditKindLabelId =
  | "chat.toolCall.edit.writing"
  | "chat.toolCall.edit.updating"
  | "chat.toolCall.edit.deleting"
  | "chat.toolCall.edit.editing"
  | "chat.toolCall.kind.write"
  | "chat.toolCall.kind.delete"
  | "chat.toolCall.kind.edit";
