// MCP Port - Model Context Protocol adapter boundary

import type { JsonSchema } from "../model/index.js";
import type { TraceContext } from "../tracing/tracer.js";
import type { McpServerFailureKind, OfficialMcpAuthPortFailureReason } from "@zcode/shared";

export type McpServerTransportType = "stdio" | "http" | "sse";
export type McpProtocolVersion = "legacy" | "auto" | "2026-07-28";
export type McpServerIsolation = "session" | "workspace";

/** The runtime origin attached by the host after public MCP configuration validation completes. */
export interface McpServerRuntimeSource {
  kind: "builtin" | "plugin";
}

export interface McpServerConfigBase {
  enabled?: boolean;
  isolation?: McpServerIsolation;
  protocolVersion?: McpProtocolVersion;
  /** Host-generated only; the public configuration schema rejects this field. */
  source?: McpServerRuntimeSource;
  timeoutMs?: number;
}

export interface McpClientCredentialsOAuthConfig {
  type: "client_credentials";
  clientId: string;
  clientSecret: string;
  clientName?: string;
  scope?: string;
}

export interface McpAuthorizationCodeOAuthConfig {
  type: "authorization_code";
  clientId?: string;
  clientSecret?: string;
  clientName?: string;
  redirectPath?: string;
  scope?: string;
}

export type McpOAuthConfig = McpAuthorizationCodeOAuthConfig | McpClientCredentialsOAuthConfig;

/**
 * The authentication declaration of the official ZCode Server MCP.
 * Allowed with `type: "http"` and `type: "stdio"`; `sse` is still rejected.
 * Both `type` and `provider` are exact values; no aliases or case variants are accepted.
 *
 * Note: this field by itself is **not** proof of official identity. Official identity is decided by the runtime-resolved ZCode API origin
 * (the host side re-validates it too); a third-party Plugin that copies this field can only make credentials flow to the real ZCode backend.
 *
 * The two shapes deliver credentials over different channels:
 * - http: the host injects the identity headers per request inside a fetch wrapper, so credentials never enter the plugin process;
 * - stdio: the requests are issued by the plugin process itself, and the identity headers ride along in the `_meta` of every outbound protocol message.
 */
export interface ZCodeOfficialMcpAuthConfig {
  type: "zcode_official";
  provider: "jwt_token";
}

/**
 * Runtime ownership info generated by the Plugin loader; `.mcp.json` cannot override it.
 * It is used for credential resolution and log correlation, and plays no part in the trust decision.
 * The target origin must pass `isOfficialMcpOriginTrusted`; plugin identity itself is not
 * an authorization filter. Destination validation and the server-side interface-permission / plan / quota validations each carry a different boundary.
 */
export interface McpOfficialProvenance {
  pluginId: string;
  /** The raw MCP key inside a Plugin (without the `plugin:<name>:` namespace prefix). */
  mcpKey: string;
  source: "plugin";
}

export interface McpStdioServerConfig extends McpServerConfigBase {
  type: "stdio";
  command: string;
  args?: string[];
  cwd?: string;
  env?: Record<string, string>;
  auth?: ZCodeOfficialMcpAuthConfig;
  /** Host-generated; it must never come from file configuration. */
  official?: McpOfficialProvenance;
}

export interface McpHttpServerConfig extends McpServerConfigBase {
  type: "http";
  url: string;
  headers?: Record<string, string>;
  oauth?: McpOAuthConfig;
  auth?: ZCodeOfficialMcpAuthConfig;
  /** Host-generated; it must never come from file configuration. */
  official?: McpOfficialProvenance;
}

export interface McpSseServerConfig extends McpServerConfigBase {
  type: "sse";
  url: string;
  headers?: Record<string, string>;
  oauth?: McpOAuthConfig;
}

export type McpServerConfig = McpStdioServerConfig | McpHttpServerConfig | McpSseServerConfig;

export type McpServerStatusKind =
  | "connecting"
  | "connected"
  | "disabled"
  | "disconnected"
  | "failed"
  | "untrusted";

export interface McpServerStatus {
  status: McpServerStatusKind;
  transport: McpServerTransportType;
  toolCount: number;
  updatedAt: string;
  error?: string;
  failureKind?: McpServerFailureKind;
  serverRequestId?: string;
  protocolEra?: "legacy" | "modern";
  authorization?: {
    type: "oauth_authorization_code";
    authorizationUrl: string;
    startedAt: string;
  };
}

export interface McpToolAnnotations {
  readOnlyHint?: boolean;
  destructiveHint?: boolean;
  idempotentHint?: boolean;
  openWorldHint?: boolean;
}

export const ZCODE_MCP_ERROR_PRESENTATION_META_KEY = "zcode/errorPresentation";
export const ZCODE_MCP_ERROR_PRESENTATION_MESSAGE_ONLY = "message-only";
/** The index of the image block in the MCP content that came from an explicit model call to tab.screenshot(). */
export const ZCODE_MCP_BROWSER_SCREENSHOT_CONTENT_INDICES_META_KEY =
  "zcode/browserScreenshotContentIndices";
/**
 * The target application identity of this node_repl cell operation, so the tool card can display an app icon.
 *
 * **Writable only by node-repl-host**: the host's CUA bridge reads the producer's
 * `zcode.cua/app-associations-v1` out of the broker response and projects it into the minimal shape here. The producer's own key can also
 * reach `_meta` via `nodeRepl.setResponseMeta` / `nodeRepl.emitStructuredResult`, and since these two
 * APIs hang off sandbox globals visible to the model, it is untrusted and must be dropped host-side (the same
 * treatment as `ZCODE_MCP_BROWSER_SCREENSHOT_CONTENT_INDICES_META_KEY`).
 */
export const ZCODE_MCP_NODE_REPL_CUA_APP_META_KEY = "zcode/nodeReplCuaApp";
/**
 * The `x-request-id` from the official Server MCP response headers, attached to a failed tool result (value is a string).
 *
 * The short prefix `zcode/` is used instead of `com.zcode/`: this is not a cross-language protocol — the server hands it over in a header and the
 * client moves it into `_meta` itself, so both production and consumption happen on the client (`com.zcode/` is reserved for keys produced
 * directly on the Go side, such as `com.zcode/mcp-unavailable`).
 *
 * It is attached only when `isError`: it is a troubleshooting clue for humans (take it to look up the server logs), and pure noise on the success path.
 */
export const ZCODE_MCP_SERVER_REQUEST_ID_META_KEY = "zcode/officialMcpServerRequestId";

export interface McpToolDescriptor {
  serverName: string;
  toolName: string;
  name?: string;
  description?: string;
  timeoutMs?: number;
  inputSchema: JsonSchema;
  outputSchema?: JsonSchema;
  annotations?: McpToolAnnotations;
  /**
   * This tool's result is **trusted enough to change the interface based on it**: it comes from an MCP server with `type: "http"` that declares
   * `auth.type = zcode_official`.
   *
   * Its only use is trusting the structured markers inside the result (an `error_code` for exhausted quota / no plan). The criterion is "who produced the result",
   * not "who the plugin is":
   * - http: the response comes from the ZCode backend. A live connection already means every request passed origin validation and failed closed,
   *   so a third-party plugin, even if it declares official auth, can only aim its requests at the real ZCode and does not get to write the response body;
   * - stdio: the result is produced by the plugin process itself and can be forged at will, so it is therefore **not set**.
   *
   * It is deliberately **not** decided by "does the plugin come from the official marketplace": that would invalidate official plugins installed from non-official sources (including local self-testing and
   * zcode-plugins-test), and it is not a real barrier anyway — see `isOfficialMcpOriginTrusted` in `@zcode/shared`.
   */
  official?: boolean;
}

export type McpContentBlock = Record<string, unknown>;

export interface McpToolCallResult {
  content: McpContentBlock[];
  structuredContent?: unknown;
  isError?: boolean;
  _meta?: Record<string, unknown>;
}

export interface McpConnectionSnapshot {
  statuses: Record<string, McpServerStatus>;
  tools: McpToolDescriptor[];
}

export interface McpConnectOptions {
  /**
   * The upper bound on waiting for an authorization_code OAuth callback.
   * The ordinary MCP timeoutMs only bounds protocol requests; session startup needs a separate limit on the OAuth authorization wait.
   */
  oauthAuthorizationTimeoutMs?: number;
  /**
   * The liveness of an existing connection is verified before it is reused (see McpPort.pingServer), and a dead one is reconnected.
   * Calls that explicitly mean "re-probe because the user asked for it", such as a Settings page refresh, must set this; session startup does not need to,
   * a connection just established in the reuse pool is enough.
   */
  revalidate?: boolean;
  signal?: AbortSignal;
  trace?: TraceContext;
  workingDirectory?: string;
  /** Identity isolation uses workspaceIdentity; it falls back to workingDirectory only when that is absent locally. */
  workspaceIdentity?: string;
}

export interface McpCallToolRequest {
  serverName: string;
  toolName: string;
  arguments?: Record<string, unknown>;
  trace?: TraceContext;
  /** The call origin; a host MCP can use it to restrict capabilities that cannot be safely inherited by a subagent. */
  runtimeScope?: "main" | "subagent";
  /** The request context is only for shared-host isolation; it does not change MCP tool parameters. */
  workspacePath?: string;
  workspaceIdentity?: string;
  workspaceKey?: string;
  remoteSessionId?: string;
  clientMode?: string;
  deliveryKind?: string;
  turnId?: string;
}

export interface McpCallToolOptions {
  signal?: AbortSignal;
  timeoutMs?: number;
}

/**
 * Port-level failure classification (the kinds where "no request is issued at all").
 * `official_mcp_origin_untrusted` may come from the adapter's local validation, or from a second validation on the host side.
 */
export type OfficialMcpAuthFailureReason = OfficialMcpAuthPortFailureReason;

export type OfficialMcpAuthHeadersResult =
  | { ok: true; headers: Record<string, string> }
  | { ok: false; reason: OfficialMcpAuthFailureReason };

/**
 * The dependency-injection port through which the MCP adapter consumes identity headers.
 * The adapter does not depend on `packages/services` directly; the Agent process asks the host for this request's identity headers through this port.
 *
 * Failures must be reported through the return value rather than by throwing; callers are forbidden from parsing the reason out of the error text.
 * `workspaceIdentity` / `workspacePath` / `pluginId` / `mcpKey` / `targetOrigin`
 * are only used for routing, second validation, and auditing, and **take no part in credential selection** — credentials are host-global state.
 */
export interface OfficialMcpAuthHeadersPort {
  resolveHeaders(input: {
    pluginId: string;
    mcpKey: string;
    targetOrigin: string;
    workspaceIdentity?: string;
    workspacePath?: string;
    signal?: AbortSignal;
  }): Promise<OfficialMcpAuthHeadersResult>;
}

/**
 * The official-MCP trust decision.
 *
 * There is only one rule: **the target origin is character-for-character equal to the current ZCode API origin (https, no username/password)**,
 * plus a local self-testing switch that only opens up http loopback. `pluginId` / `mcpKey` are passed in only for logging and credential-resolution
 * attribution, and **do not affect the outcome** — the old "must be an official marketplace plugin" check was removed in 2026-08
 * (it made it impossible for official plugins to self-test against the real endpoint before release, and a third-party plugin could read the very same credential
 * through a hook anyway, so it was never a real barrier).
 *
 * The implementation lives in `@zcode/shared`: host and adapter share the same one copy, so that one side never allows what the other refuses.
 * It is async so that the host side can resolve the origin with settings overrides applied.
 */
export interface OfficialMcpTrustedOriginRegistry {
  isTrusted(input: { pluginId: string; mcpKey: string; origin: string }): Promise<{
    detail?: string;
    trusted: boolean;
  }>;
}

export interface McpPort {
  connectConfiguredServers(
    servers: Record<string, McpServerConfig>,
    options?: McpConnectOptions,
  ): Promise<McpConnectionSnapshot>;
  connectServer(
    name: string,
    config: McpServerConfig,
    options?: McpConnectOptions,
  ): Promise<McpServerStatus>;
  disconnectServer(name: string): Promise<McpServerStatus | undefined>;
  /**
   * Actively probes whether the connection is still alive; returning false means the transport is broken.
   * When an HTTP/SSE MCP is stopped it does not dispatch onclose, and status() stays on connected for a long time;
   * only an explicit ping can expose this "silent death". The implementation is optional: when it is absent, callers treat the connection as alive.
   */
  pingServer?(name: string, options?: { timeoutMs?: number }): Promise<boolean>;
  status(): Promise<Record<string, McpServerStatus>>;
  listTools(): Promise<McpToolDescriptor[]>;
  callTool(request: McpCallToolRequest, options?: McpCallToolOptions): Promise<McpToolCallResult>;
  close(): Promise<void>;
}
