// GENERATED by `cargo run -p zcode-packaging -- gen-targets`. Do not edit by hand.
// Source of truth: packages/rust/crates/zcode-packaging/src/target.rs
//
// `cargo test -p zcode-packaging` regenerates this file and byte-compares, so a
// hand edit fails the test rather than silently drifting from the packager (spec P4).

export const NATIVE_PLATFORM_SUFFIXES = {
  "darwin-arm64": "darwin-arm64",
  "darwin-x64": "darwin-x64",
  "linux-arm64": "linux-arm64-gnu",
  "linux-x64": "linux-x64-gnu",
  "win32-arm64": "win32-arm64-msvc",
  "win32-x64": "win32-x64-msvc",
} as const;

export type NativePlatformKey = keyof typeof NATIVE_PLATFORM_SUFFIXES;

export const NATIVE_PLATFORM_KEYS = Object.keys(
  NATIVE_PLATFORM_SUFFIXES,
) as NativePlatformKey[];
